### ISSUE TITLE
More ideas for potential features

### ISSUE THREAD

**Issue by Gajus84** [sxyazi/yazi#85] opened 2023-08-25 05:10 UTC
As I was encouraged to do so, while using Yazi I thought of other points which could be useful:

1.) Possibly even be called a bug: Currently Yazi does not honor the full selection made when copying or cutting. Similar to #84 , only the files (selection) of the current folder are included. This is not very intuitive in my opinion. Why should my selection be limited to my current location? 

2.) In addition, a display of the number of currently selected/cut/copied files would be nice. The solution of LF could offer inspiration for this. Here the number is displayed in a small field and via colorcode whether the display indicates marked, copied ect. 

Examples:

5 selected files
![2023-08-25T06:50:58,749157660+02:00](https://github.com/sxyazi/yazi/assets/44810947/8f23bd3c-ec67-4b7a-aba8-1216d87f6561)

5 yanked files
![2023-08-25T06:51:45,755027932+02:00](https://github.com/sxyazi/yazi/assets/44810947/7c765e29-1939-4634-bb2b-3ababe7a9266)

3.) Display Name in Keymap. As already described this would contribute strongly to the overview. Is this possibly related to #79?

4.) The possibility for more information about the files. A file manager should provide a quick overview of my file system. For this it can be helpful to be able to capture appropriate metadata, such as size, access rights, creation date and last modification at a glance.

**Comment by sxyazi** [comment] 2023-08-25 06:11
1: This is expected behavior and is intended to simplify the design, but there is indeed a bug here, which is documented in the feature requests -- the previous directory selection should be cleared on enter or leave.

2, 4: I did think about improving them, but just didn't have the time... I'm currently spending my time on bug fixes and implementing some features that may need to be refactoring the current architecture, and I need to have the architecture finalized in advance to lay the groundwork for later extensions. Which 4 I'd like to implement is a floating window, like the tasks list does, where the necessary info about a file is listed.

3: Yazi supports combining multiple commands (although support is limited right now and will be enhanced later), so perhaps it would be better to set the description manually

**Comment by Gajus84** [comment] 2023-08-25 06:42
Thank you for your quick and detailed reply. 

I appreciate your hard work and I'm well aware that those things are all simply quality of life features. I'm using Yazi as my main File Manager already after all.

**Comment by sxyazi** [comment] 2023-08-30 14:12
> 3.) Display Name in Keymap

Done by https://github.com/sxyazi/yazi/pull/93, please give it a try!

> 1.) Possibly even be called a bug

Refer to https://github.com/sxyazi/yazi/issues/85#issuecomment-1692819360, the bug has been logged in Feature Requests.

> 2.) In addition, a display of the number of currently selected/cut/copied files
> 4.) The possibility for more information about the files.

I have added these two to the Feature Requests.

---

I would like to close this issue if the `Display Name in Keymap` works as expected, in favor of the Feature Requests list.

**Closed** 2023-08-30 17:17 UTC

**Comment by Gajus84** [comment] 2023-08-30 17:33
> > 3.) Display Name in Keymap
> 
> Done by #93, please give it a try!
> 
Tested and works perfectly. Closed this :)

**Comment by sxyazi** [comment] 2024-02-15 15:02
Hey! Your feature request "Display of the number of currently selected/cut/copied files" has been done by @Rolv-Apneseth in https://github.com/sxyazi/yazi/pull/646 🎉

**Comment by sxyazi** [comment] 2024-11-20 08:47
> The possibility for more information about the files

Done in https://github.com/sxyazi/yazi/pull/1802 - all feature requests for this issue are now complete 🎉
