### ISSUE TITLE
Reload "search result via fd" after action on file

### ISSUE THREAD

**Issue by MediumRar** [sxyazi/yazi#713] opened 2024-02-23 11:56 UTC
### Please describe the problem you're trying to solve

Whenever I "search for files via fd" and then delete one of the displayed (found) files, the file remains displayed. I did not try this with any other functionality (moving etc.) but I would guess that this affects multiple actions.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Search result should automatically be updated to exclude deleted file(s).

**Comment by sxyazi** [comment] 2024-02-23 12:01
Duplicate of https://github.com/sxyazi/yazi/issues/62

Thanks for the report, this is a known issue, closing in favor of https://github.com/sxyazi/yazi/issues/62

**Closed by sxyazi** 2024-02-23 12:01 UTC
Labels: feature
