### ISSUE TITLE
Korean Character looks broken (Unicode Normalization support request)

### ISSUE THREAD

**Issue by jaekong** [sxyazi/yazi#1714] opened 2024-10-02 11:32 UTC
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.36.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Nixpkgs 2024-09-04)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.3 (Nixpkgs 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some("/private/tmp/com.apple.launchd.JDjRNbLrNt/org.xquartz:0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/etc/profiles/per-user/jae/bin/fish")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/jae/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

<img width="2560" alt="Screenshot 2024-10-02 at 7 50 12 PM" src="https://github.com/user-attachments/assets/3cb131b5-939f-48d7-ab8c-6a562393d201">

All of those filenames showing "ㅅㅋㄹㅅ" should be "스크린샷" but Yazi shows only the first part of the Unicode combining codepoints.

I suspect it's because Yazi does not properly normalize unicode, since when I manually normalize the names, it works as expected.

<img width="2560" alt="Screenshot 2024-10-02 at 8 07 46 PM" src="https://github.com/user-attachments/assets/648d81e4-d7f8-48c2-a28e-7e8f4965a518">
<img width="251" alt="Screenshot 2024-10-02 at 8 08 54 PM" src="https://github.com/user-attachments/assets/69590549-779a-4778-8486-90b4794986de">

(both folders should say "가나다라마" (or "가나다라마 copy") but in Yazi the one I manually normalized says 가나다라마, the copy does not)

### Additional Notes

I am not sure about this, but all the white dots appearing on the preview pane in the first screenshot seem to be some of the "leftover" Korean codepoints (ㅏㅏㅏㅏㅏ from 가나다라마 or ㅡㅡㅣㅑㅅ from 스크린샷). They only appear when I have a filename containing Korean displayed.

Interestingly, Japanese, French, Vietnamese characters works fine. French and Vietnamese may be because they are use latin characters and they have a single unicode scalar though. Which makes me think maybe it's not Normalization? or maybe it's normalization but only for Korean for some reason? Korean combining characters change how the first character of the combining sequence looks like, so maybe it still is normalization, but affects different languages differently. (for instance, 과 and ㄱ overlayed on top of ㅘ looks a lot different, not only because it's two characters but also because the positioning and proportion changes, unlike は + "゙ and ば or a +  ̄ and ā)

In any case, 

### Unicode Normalization

Lots of languages in Unicode needs composition, and Unicode has support for various methods of composition.

Unfortunately, Terminals usually don't work so nicely with decomposed codepoints (especially if it's from full-width character set like CJK) and macOS by default, uses NFD normalization scheme which decomposes all unicode characters. (가 -> ㄱ + ㅏ)

So, in effect, many TUI apps breaks when they see NFD normalized characters. Solution to this would be normalize the names in NFC scheme, which combines all of the combining Unicode codepoints and gives you a single character that represents combined character. (ㄱ + ㅏ -> 가)

### Minimal reproducer

View any Korean file name in Yazi.

### Anything else?

I have not tried Nightly build because I have searched the main branch and could not find any reference to unicode normalization, So I assumed there's no existing code addressing this problem.

**Comment by sxyazi** [comment] 2024-10-02 12:36
I can reproduce it with:

```rust
use ratatui::text::Span;

fn main() {
  let mut terminal = ratatui::init();

  _ = terminal.draw(|frame| {
    let greeting = Span::raw("가나다라마");
    frame.render_widget(greeting, frame.area());
  });

  std::thread::sleep(std::time::Duration::from_secs(5));
  ratatui::restore();
}
```

Looks like a Ratatui bug - will report it.

**Comment by sxyazi** [comment] 2024-10-02 13:07
Reported upstream, closing in favor of https://github.com/ratatui/ratatui/issues/1396

**Closed by sxyazi** 2024-10-02 13:07 UTC
Labels: bug, upstream
