### ISSUE TITLE
The path splitting of the `cd` command is incorrect in windows

### ISSUE THREAD

**Issue by DreamMaoMao** [sxyazi/yazi#850] opened 2024-03-29 08:26 UTC
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

```

</details>

### Describe the bug

```toml
{ on = [ "g", "d" ],       run = "cd E:\\down",   desc = "Go to down" },
```
this config is not work normally, because the parent path is `E:` instead of `E:\down` after cd `E:\down`.

so if i enter any path in `E:\down`, i can't go back to the `E:\down` 

https://github.com/sxyazi/yazi/assets/30348075/a80a7a4d-8dfe-4045-95eb-40f5683b4a7f

### Expected Behavior

```
	{ on = [ "g", "d" ],       run = "cd E:\\down",   desc = "Go to down" },
```

after toggle `gd`

the parent path should be  `E:\down`  after enter a folder in `E:\down`.

### To Reproduce

1. use the config like this
```
	{ on = [ "g", "d" ],       run = "cd E:\\down",   desc = "Go to down" },
```

2. keydown `gd` to open `E:\down`

3.enter a folder in `E:\down`

4.try to go back to  `E:\down`  by keydown `h`

### Configuration

```toml
	{ on = [ "g", "d" ],       run = "cd E:\\down",   desc = "Go to down" },
```

**Comment by sxyazi** [comment] 2024-04-14 16:04
You need to use `cd 'C:\\Users'` because `\\` is escaped to `\` in toml, but `\` is a special character in the shell commands. 

Closing as this is the expected behavior.

**Closed by sxyazi** 2024-04-14 16:04 UTC
Labels: bug
