### ISSUE TITLE
GIF preview doesn't work with ueberzugpp

### ISSUE THREAD

**Issue by danjenson** [sxyazi/yazi#1620] opened 2024-09-08 18:51 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.13.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (9483798 2024-09-08)
    Debug  : true
    OS     : linux-x86_64 (unix)

Ya
    Version: ya 0.2.5

Emulator
    Emulator.via_env: ("alacritty", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/home/danj/.cargo/bin/nu")
    EDITOR             : Some("hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

It looks like `yazi` creates a temporary preview of a `gif` in the /tmp directory, but this is only a single frame.

### Minimal reproducer

1. Install yazi: `cargo install yazi --locked`
2. Add a gif to the current directory
3. Preview with yazi: `./yazi/target/debug/yazi .`
4. View log: `{"action":"add","identifier":"yazi","x":53,"y":1,"max_width":67,"max_height":25,"path":"/tmp/yazi-1000/01d9e6c5eef010593b0b2753f663c0ce"}`
5. Check file type: `file /tmp/yazi-1000/01d9e6c5eef010593b0b2753f663c0ce #JPEG`
6. Check original file type: `file my.gif # GIF` 
7. Use `ueberzugpp layer` with `{"action":"add","identifier":"yazi","x":53,"y":1,"max_width":67,"max_height":25,"path":"/tmp/yazi-1000/01d9e6c5eef010593b0b2753f663c0ce"} # static image`
8. Use `ueberzugpp layer` with updated `my.gif` path `{"action":"add","identifier":"yazi","x":53,"y":1,"max_width":67,"max_height":25,"path":"my.gif"} # works`

### Anything else?

Here is my `yazi.toml`:
```toml
[manager]
ratio = [1, 2, 6]
sort_by = "natural"

[preview]
max_width = 1600
max_height = 1200
```
I tested commenting out the preview block, but no change.

**Comment by sxyazi** [comment] 2024-09-09 06:15
Hi, this is the expected behavior because Yazi doesn’t support GIFs yet. I plan to try supporting it in the future (already included in the [Feature Requests](https://github.com/sxyazi/yazi/issues/51)). 

This will require testing different image backends (Kitty, Sixel, IIP, Ueberzug) and finding a way to handle GIFs. It might also involve introducing a few different options, using the one with the worst performance as the baseline to ensure all users can use it.

Closing as it's an unsupported feature rather than a bug, and it's already included in the feature requests.

**Closed by sxyazi** 2024-09-09 06:15 UTC
Labels: bug
