### ISSUE TITLE
Moving folder into itself causes frozen task

### ISSUE THREAD

**Issue by 404Wolf** [sxyazi/yazi#1480] opened 2024-08-14 04:52 UTC
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Kitty 0.35.2

### `yazi --debug` output

```Shell

Yazi
    Version: 0.3.0 (71d6b0d 2024-08-12)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/run/current-system/sw/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-35
    fzf              : 0.54.2
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : 24.07
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/wolf/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

If you select some folders, cut them (x), and then go into a subdirectory, and then paste them in that subdirectory, including one of the folders you selected, then your tasks will show 99% complete, even though the folders did move correctly.

### Minimal reproducer

`cd $(mktemp -d)` to enter a new temporary directory. Open yazi there. `a` to create a new directory, name it `foo/` (with the slash). Now do the same thing to create `bar/` and `buzz/`. Walk to the top of the current folder list with `gg`. Press `v` to enter select mode, and `shift G` to go down to select them all. Press `x` to cut them. Now walk into `foo/` with `l`. Paste them with `p`. Now look and see on the bottom right "99% done 1 left," and if you try to exit with `q` it will tell you a task is still pending.

### Anything else?

![f5307119-f683-4bf6-a11e-8c26cd4815eb](https://github.com/user-attachments/assets/13ad9449-7a43-4c93-8675-725a87f481ab)

**Comment by sxyazi** [comment] 2024-08-14 04:58
Press `w` to open the task manager, then press `Enter` on the task to inspect it to see what the error is

**Comment by 404Wolf** [comment] 2024-08-14 06:38
That helps! Maybe this isn't a bug in that case, it just seems anti-intuitive, I feel like there should be some sort of indication when there are errors for tasks. "Cannot cut directory into itself." 

> Press `w` to open the task manager, then press `Enter` on the task to inspect it to see what the error is

**Comment by sxyazi** [comment] 2024-08-14 07:07
OK, in this case, I'll close this issue because it's the expected behavior—Yazi doesn't allow copying a directory into itself for safety reasons. This check was introduced in https://github.com/sxyazi/yazi/pull/925.

Also, when a task fails, the progress bar turns red instead of blue to indicate the failure. I believe this is already quite intuitive

**Closed by sxyazi** 2024-08-14 07:07 UTC
Labels: bug
