### ISSUE TITLE
Use LS_COLORS for theming

### ISSUE THREAD

**Issue by knolljo** [sxyazi/yazi#697] opened 2024-02-18 20:43 UTC
### Is your feature request related to a problem? Please describe

LS_COLORS is an env var used by ls and others (gokcehan/lf or eza) to colorize files and directories, it would be a perfect fit for yazi.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Maybe some config or command-line option would be great, such that there is no conflict with colors in theme.toml

**Comment by sxyazi** [comment] 2024-02-19 09:03
Duplicate of https://github.com/sxyazi/yazi/issues/450

Why do you want `LS_COLORS` instead of the Yazi theme? afaik, `LS_COLORS` only supports filenames/extensions, while Yazi supports mime-type, filetype (exec, link, orphan, sock, etc) in addition to that.

**Comment by sxyazi** [comment] 2024-02-21 10:33
You can write a script using [lscolors](https://github.com/sharkdp/lscolors) to parse your LS_COLORS content, turning

```
*README               38;5;220;1
.log                  38;5;190
```

into

```bash
# theme.toml
[filetype]

rules = [
  { name = "*README", fg = "#aaaaaa" },
  { name = "*.log",   fg = "#bbbbbb" }
]
```

**Comment by sxyazi** [comment] 2024-03-01 04:28
Closing as duplicate and not in the plan

**Closed by sxyazi** 2024-03-01 04:28 UTC
Labels: feature

**Comment by Mellbourn** [comment] 2024-03-01 18:44
> Why do you want `LS_COLORS` instead of the Yazi theme?

Because I'm using https://github.com/trapd00r/LS_COLORS, which provides colors for over 300 different file types. So, my `ls` is much richer in color than yazi is. It is the one thing I miss in yazi, compared to xplr.

The color themes currently provided in yazi do indeed use mime types, which is nice I guess, but in practice it results in much fewer colors.

example folder in yazi:
<img width="154" alt="image" src="https://github.com/sxyazi/yazi/assets/1785727/0be73456-3257-448c-9ac1-e583540e44bd">
same files in `lsd`, colored by `LS_COLORS`:
<img width="152" alt="image" src="https://github.com/sxyazi/yazi/assets/1785727/cc4ddd03-56a4-4abf-8362-cce581b4c612">
same files in `xplr`:
<img width="161" alt="image" src="https://github.com/sxyazi/yazi/assets/1785727/924ebfbf-6eff-4c05-a135-b5ee63c4ddfd">

**Comment by Mellbourn** [comment] 2024-03-01 21:14
I've created a small node program to convert `LS_COLORS` to the corresponding `theme.toml` format.

The program is here https://github.com/Mellbourn/lsColorsToToml

I used it to create [my own theme file ](https://github.com/Mellbourn/dotfiles/blob/main/.config/yazi/theme.toml)

**Comment by knolljo** [comment] 2024-03-02 08:31
Exactly what I wanted to do, but didn't had the time. Thanks for sharing!

**Comment by knolljo** [comment] 2024-03-05 15:15
I've also created a python script to convert LS_COLORS to toml.
It can be found here [gist](https://gist.github.com/knolljo/5e4ceb7695bc0d59c5274314569e8b1f)
