### ISSUE TITLE
GDrive Implementation

### ISSUE THREAD

**Issue by sedobrengocce** [sxyazi/yazi#619] opened 2024-02-02 13:16 UTC
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

A configuration to connect gmail account and mount drive and shared drive to a configured directory

**Comment by sxyazi** [comment] 2024-02-02 13:29
Duplicate of https://github.com/sxyazi/yazi/issues/611

**Closed by sxyazi** 2024-02-02 13:29 UTC
Labels: feature
