### ISSUE TITLE
File colors appear only once yazi enters the directory that contains these files.

### ISSUE THREAD

**Issue by yousef8192** [sxyazi/yazi#1326] opened 2024-07-22 22:31 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

terminator 2.1.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####

Yazi
    Version: 0.2.5 (c65a14c 2024-04-23)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("screen-256color", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/bash")
    EDITOR: Some("vim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.44\nmagic file from /etc/magic:/usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "opener \"$@\"", block: true, orphan: false, desc: "Open", for_: None, spread: true })
    block: Some(Opener { run: "opener \"$@\"", block: true, orphan: false, desc: "Open", for_: None, spread: true })

tmux
    TMUX: true

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/yousef/.local/state/yazi" directory.



```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

I have a directory named test-dir that contains an image file named test.png.
If I am in the parent directory that contains test-dir and the cursor is at test-dir, then  test.png has no color in the preview pane (its color is the default white color). 
If I enter test-dir test.png gets colored as expected.
If I return back to the parent directory that contains test-dir and once again place the cursor at test-dir, test.png is colored just fine. 

Here's an illustration of what I mean :

1. Present in the parent directory that contains test-dir and the cursor is at test-dir
![image](https://github.com/user-attachments/assets/f294c37b-72da-460e-afa7-c3ec1f1adc7d)

2. Enter test-dir
![image](https://github.com/user-attachments/assets/a36f7c0c-66eb-4de5-aeb3-531e7f9af43d)

3. Return back to the parent directory that contains test-dir and the cursor is at test-dir
![image](https://github.com/user-attachments/assets/c35d1ede-76cf-4f31-8100-cc21974e0061)

What I tested is the latest release as of the time of writing this issue (Yazi 0.2.5 (c65a14c 2024-04-23) is the output of yazi --version).  I am not really sure which build is considered the latest nightly build so I can't confirm if I tried it or not sorry. Please let me know which one is it and I will try it to see if the issue exists there too. 

If any further information is needed please let me know.
Thanks a lot for the amazing tool!! 

### Expected Behavior

All files should appear with the colors associated with their filetype whether the user navigated to the directory that contains them or not.

### To Reproduce

1. Create a directory named test-dir and place in it any file that has a certain color associated with its filetype.

2. Navigate to the parent directory that contains test-dir and place the cursor at test-dir.

3. Enter test-dir.
 
4. Return back to the parent directory that contains test-dir and place the cursor at test-dir.

### Configuration

Tested without configurations

**Comment by sxyazi** [comment] 2024-07-22 23:58
This is by design - to maximize performance, Yazi only lazily loads the mimetype for files in the current working directory of that page, hence the mimetype for files in the preview pane isn't loaded at all, which is why the `mime` rules aren't working. 

If you really need it, I recommend using `name` and `if` rules instead, https://yazi-rs.github.io/docs/configuration/theme#filetype

Closing as this is the expected behavior.

**Closed by sxyazi** 2024-07-22 23:58 UTC
Labels: bug

**Comment by leihaojun** [comment] 2024-08-12 10:35
i found a plugin to make the preview  folder color work:

https://gitee.com/DreamMaoMao/mime-preview.yazi
