### ISSUE TITLE
Ctrl-z sometimes break yazi

### ISSUE THREAD

**Issue by ricardoseriani** [sxyazi/yazi#1309] opened 2024-07-18 13:19 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (VERGEN_IDEMPOTENT_OUTPUT 2024-04-23)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/zsh")
    EDITOR: Some("vim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /etc/magic:/usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/rseriani/.local/state/yazi" directory.
```
</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When I press ctrl-z to suspend yazi and then run fg to bring it back to foreground, the window is "freeze/broken".
This sometimes occurs, but not always, so you may need a few tries to reproduce.

### Expected Behavior

Yazi should be working when it's back to foreground.

### To Reproduce

run `yazi`
press `ctrl-z`
run `fg` to bring it back to foreground
try using `yazi` normally 

### Configuration

no config

### Anything else?

![2024-07-18_10-13](https://github.com/user-attachments/assets/497609fd-69a9-4576-90b0-b4b01433d2ea)

**Comment by sxyazi** [comment] 2024-07-18 13:48
I made some fixes to the behavior of Ctrl-Z earlier in https://github.com/sxyazi/yazi/pull/1307, please give it a try

**Comment by ricardoseriani** [comment] 2024-07-18 15:02
I tried applying the PR locally, but I'm not really sure if this is the correct way:

- `git pull origin pull/1307/head:ctrl-z`
- `git switch ctrl-z`
- `cargo build --release --target=x86_64-unknown-linux-musl`
- `./target/x86_64-unknown-linux-musl/release/yazi`

Apparently, the PR was applied.

If what I was made is correct, unfortunately, the problem still persists.

**Comment by sxyazi** [comment] 2024-07-18 15:33
What does the `yazi --debug` output look like? Does it include the hash of that commit? Can you record a gif so I can see your steps and what happens?

**Comment by ricardoseriani** [comment] 2024-07-18 17:12
### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (d88211c 2024-07-18)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("vim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: tmux 3.2a

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.54.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 
    zoxide           : No such file or directory (os error 2)
    unar             : 1.10.1
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/rseriani/.local/state/yazi" directory.
```
</details>

Video record of the problem

https://github.com/user-attachments/assets/307cd69d-b780-4d90-a69c-c4c1ded71b21

**Comment by sxyazi** [comment] 2024-07-18 17:47
Hi, I made a new PR, please try https://github.com/sxyazi/yazi/pull/1310

**Comment by ricardoseriani** [comment] 2024-07-18 23:58
I tried it, and the problem still persists.
But now, when this occurs, I can press `ctrl-z` to stop yazi and then send it back to foreground with `fg` and it's back working again.

**Comment by sxyazi** [comment] 2024-07-19 07:42
That's so weird, with https://github.com/sxyazi/yazi/pull/1310/commits/fa297b31c04ee1c1b2f26b3b4ebca8d4b533899e, I can't reproduce it on my Linux VM anymore, no matter how many times I try, it works fine for me. 


https://github.com/user-attachments/assets/b7ad3d9d-426f-4f73-b13b-9a7a1ed27f13


Are you sure you're using that commit right? Did I miss any details to reproduce it?

**Comment by sxyazi** [comment] 2024-07-19 13:51
Please apply these two patches *separately* on top of that PR and see what happens:

```diff
--- yazi/yazi-fm/src/app/commands/resume.rs
+++ yazi/yazi-fm/src/app/commands/resume_new.rs
@@ -4,7 +4,6 @@
 
 impl App {
 	pub(crate) fn resume(&mut self, _: Cmd) {
-		self.cx.manager.active_mut().preview.reset_image();
 		self.term = Some(Term::start().unwrap());
 
 		// While the app resumes, it's possible that the terminal size has changed.
```


```diff
--- yazi/yazi-fm/src/app/commands/resume.rs
+++ yazi/yazi-fm/src/app/commands/resume_new.rs
@@ -4,13 +4,12 @@
 
 impl App {
 	pub(crate) fn resume(&mut self, _: Cmd) {
-		self.cx.manager.active_mut().preview.reset_image();
+		self.signals.resume(None);
+
 		self.term = Some(Term::start().unwrap());
 
 		// While the app resumes, it's possible that the terminal size has changed.
 		// We need to trigger a resize, and render the UI based on the resized area.
 		self.resize(());
-
-		self.signals.resume(None);
 	}
 }
```

**Comment by ricardoseriani** [comment] 2024-07-19 14:33
I tried both separately, but it still doesn't work.

**Comment by sxyazi** [comment] 2024-07-19 14:41
I have no idea then. After applying that PR, the issue completely disappeared for me, and before applying that PR, I could reproduce it with the Linux + WezTerm combo (it couldn't be reproduced on non-Linux systems or without WezTerm).

I'll keep it open for a while to see if anyone else encounters it and can provide more clues and help debug it.

**Comment by sxyazi** [comment] 2024-09-17 09:45
This issue has been open for 2 months, no other users have reported encountering it, I can't reproduce it either, so I'm going to close it since it's not doable for me and no one can help :(

My best guess is that this is related to your environment, or it's already been fixed in recent versions.

**Closed by sxyazi** 2024-09-17 09:45 UTC
Labels: bug, help wanted, cant reproduce
