### ISSUE TITLE
FAT32 USB flash, can't copy/paste anything

### ISSUE THREAD

**Issue by skafiend** [sxyazi/yazi#2036] opened 2024-12-12 16:37 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.37.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.2 (c78f39b5 2024-12-12)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.82.0 (f6e511ee 2024-10-15)

Ya
    Version: 0.4.2 (c78f39b5 2024-12-12)

Emulator
    Brand.from_env      : Some(Kitty)
    Emulator.detect     : Emulator { kind: Left(Kitty), light: false, cell_size: Some((10, 23)) }
    Emulator.detect_full: Ok(Emulator { kind: Left(Kitty), light: false, cell_size: Some((10, 23)) })

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.2

Variables
    SHELL           : Some("/bin/bash")
    EDITOR          : Some("nvim")
    VISUAL          : Some("nvim")
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: Some("--color=fg:#af00ff,bg:#011627,hl:#ffffff --color=fg+:#011627,bg+:#af00ff,hl+:#ffffff --color=info:#af00ff,prompt:#ffffff,pointer:#011627 --color=marker:#FFFFFF,spinner:#af00ff,header:#0000ff,gutter:#011627,border:#011627")

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.45
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 6.1.2 / 6.1.2
    pdftoppm      : No such file or directory (os error 2)
    magick        : 7.1.1-41
    fzf           : 0.56.3
    fd/fdfind     : 10.1.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : 1.10.3
    zoxide        : 0.9.4
    7z/7zz        : 16.02 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : 0.13
    xsel         : 1.2.1
```

### Describe the bug

yazi seems to be extremely sluggish when I copy files on an external fat 32 drive (I've tried two different ones and had the same issue). it takes about an hour maybe even more to transfer less than 1000 MB. if I do the same using cp or ranger it takes just several minutes

### Minimal reproducer

1. format a usb stick to fat 32
2. copy a bunch of files (300-500 mb total)
3. progress goes from 0 to 93% pretty fast
4. ...
5. you are stuck and nothing happens

### Anything else?

![2024-12-12_18-58](https://github.com/user-attachments/assets/5f24f3a2-6d24-420e-8d93-252c4800c6ce)
![2024-12-12_19-10](https://github.com/user-attachments/assets/6c4a2515-dbdd-42fe-8d80-967b0f2c06bb)
![2024-12-12_19-17](https://github.com/user-attachments/assets/0935bbde-9670-4904-9c24-efc092ed0484)
![2024-12-12_19-22](https://github.com/user-attachments/assets/45a445d2-387f-4fdd-abf7-9059b732817a)

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [x] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [x] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment] 2024-12-12 19:25
It looks like a duplicate of https://github.com/sxyazi/yazi/issues/1858. Yazi simply calls Rust's [`std::io::copy()`](https://doc.rust-lang.org/beta/std/io/fn.copy.html) when copying files, which could be a bug in Rust itself. I have a few things to confirm:

- Does this issue exist in the previous version v0.3.3? Yazi 0.4 changed the file copy API from [`std::fs::copy()`](https://doc.rust-lang.org/beta/std/fs/fn.copy.html) to [`std::io::copy()`](https://doc.rust-lang.org/beta/std/io/fn.copy.html) because `fs::copy()` had a [bug causing network file permission errors](https://github.com/sxyazi/yazi/issues/1703).
- Is the file you're copying never completing, or does it eventually complete but take a long time? Are there any error logs—can you inspect the task in Task Manager by pressing `<enter>`?
- Does this happen occasionally, or is it 100% of the time? Does it happen with a single file or only when copying multiple files?
- What happens if you manually call [`std::io::copy()`](https://doc.rust-lang.org/beta/std/io/fn.copy.html) on these files in a Rust app?

**Comment by skafiend** [comment] 2024-12-13 10:00
- yazi 0.3.3
![start](https://github.com/user-attachments/assets/153f5a95-f93f-437f-8046-2aba97d9df1c)
![middle](https://github.com/user-attachments/assets/658a58b8-28ce-4298-b314-294b56507b17)
![end](https://github.com/user-attachments/assets/d49cd873-08cf-41ed-bafe-cb980d45fb3b)
- yazi 0.4.2
![start](https://github.com/user-attachments/assets/62900a97-44d4-4950-b011-92c99abbdfb0)
![middle](https://github.com/user-attachments/assets/1ba9d32c-0d6a-4345-8e9c-28b7c17fe6a8)
![end](https://github.com/user-attachments/assets/5eac1b66-c923-404f-a034-0807277ffe3f)

I've done a couple more tests, and the yazi version doesn't affect the behavior, what usb stick I use and how many files are copied at a time does. 
- Actions Semiconductor Co., Ltd D-Wave 2GB MP4 Player / AK1025 MP3/MP4 Player - I can reproduce the issue every time as long as I transfer more than 20-25 files (each from 5 - 10mb), but when the files are compressed into a zip archive, everything works flawlessly. 
- SanDisk Corp. Cruzer Blade - works fine either way, even tho it has the same FAT32 fs

cp gives consistent results for both drives: 
![cp_test](https://github.com/user-attachments/assets/c9627b33-0cce-4f25-a8be-bc52295db065)

- What happens if you manually call [std::io::copy()](https://doc.rust-lang.org/beta/std/io/fn.copy.html) on these files in a Rust app?

I have no idea. I've never messed with rust before. Is there any way to launch yazi in debug mode, so it would generate a log file with the last file operations?

**Comment by sxyazi** [comment] 2024-12-13 21:18
In this case, if it only happens on certain USB drives, I *guess* it might be a hardware issue — some hardware might have issues with concurrent read/write operations, although I can't reproduce it on my FAT32 USB. 

You could try setting both `micro_workers` and `macro_workers` to `1` to revert the `cp` behavior, meaning force Yazi to only use a single thread for file copying, and see if it works:

https://github.com/sxyazi/yazi/blob/c78f39b50f04fb23c8376369d6c9a21226002d9c/yazi-config/preset/yazi-default.toml#L81-L83

**Comment by skafiend** [comment] 2024-12-13 21:24
![2024-12-14_00-23](https://github.com/user-attachments/assets/d377abf1-fcea-4e11-b727-87b17fd7e554)
I think it did the trick. Thank you

**Comment by sxyazi** [comment] 2024-12-13 21:32
Nice to see it's working! 

I'll create a PR later to choose more conservative values for the preset `micro_workers` and `macro_workers`, even though it might be a bit slower, but the goal is to ensure it's safe for all users as much as possible. 

But of course, users can always adjust them in their own config as needed, I think that's enough.

**Closed** 2024-12-14 00:02 UTC
Labels: bug
