### ISSUE TITLE
Images not being updated in terminal preview

### ISSUE THREAD

**Issue by awarebayes** [sxyazi/yazi#516] opened 2024-01-15 12:40 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Wezterm

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

Haven't seen a MR fixing this.

I want to preview images in terminal and look for updates. Yazi caches image previews and does not account for image update.

### Expected Behavior

When the image updates, the preview should also update

### To Reproduce

Create an image

Open the directory with the image in yazi

Open image in gimp and modify it

Look at the same image in yazi again. You may close and open yazi.

It is not updated.

### Configuration

no config

### Anything else?

None

**Comment by sxyazi** [comment] 2024-01-15 15:15
A duplicate of https://github.com/sxyazi/yazi/issues/261, should be fixed in the main branch.

**Closed by sxyazi** 2024-01-15 15:15 UTC
Labels: bug
