### ISSUE TITLE
Show "Permission denied" instead of "No items" if suitable

### ISSUE THREAD

**Issue by Ape** [sxyazi/yazi#1274] opened 2024-07-08 15:48 UTC
### Please describe the problem you're trying to solve

Currently, if I try to list files in a folder where I don't have the file permissions to do so, yazi will simply show "No items", which looks like an empty directory.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Should show "Permission denied" if that's the case.

**Comment by sxyazi** [comment] 2024-07-08 22:33
Duplicate of https://github.com/sxyazi/yazi/issues/1137, closing in favor of that

**Closed by sxyazi** 2024-07-08 22:33 UTC
Labels: feature
