### ISSUE TITLE
Unexpected line breaks on a special file name

### ISSUE THREAD

**Issue by hatute** [sxyazi/yazi#760] opened 2024-03-02 03:20 UTC
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

Kitty 0.32.0

### Yazi version

yazi 0.2.3 (Homebrew 2024-02-07)

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

There is a kind of file named as `Icon\r` (yes, there is a "\r" inside), which is used for change the icon for the current folder. It is a empty file and with no filename extension. When you move the cursor to that line, it will break the layout with a blank line. If there are several `Icon\r`s in the subfolder, when you move through them, they will make everything in chaos.

Good news is I did not use the custom icon for folders in MacOS any more, so I delete them, and everything is back to normal. So my suggestion is could you check the string part for extracting file/folder name. The bug is if there is a "\r", the layout will immediately print a new line as the `\r` expected. 

Here is the screenshot I reproduced:

![screenshot_2024-03-01 22 17 07](https://github.com/sxyazi/yazi/assets/15870636/7fd19f09-221c-4890-9da6-aaa36951c649)

### Expected Behavior

No linebreak at `Icon\r`

### To Reproduce

`touch $'Icon\r'`

### Configuration

Nothing with the configuration

**Comment by sxyazi** [comment] 2024-03-02 03:35
Duplicate of https://github.com/sxyazi/yazi/issues/709


Hi, thanks for reporting!

I noticed you're not using the latest main branch - this issue has been fixed in the latest HEAD.

**Closed by sxyazi** 2024-03-02 03:35 UTC
Labels: bug
