### ISSUE TITLE
Open / Watched Folders do not update?

### ISSUE THREAD

**Issue by nPHYN1T3** [sxyazi/yazi#1632] opened 2024-09-10 16:34 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Kitty

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0.0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("/usr/bin/nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.54.3
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

Log
```
  2024-09-10T16:27:40.182398Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
    at yazi-adapter/src/emulator.rs:73

  2024-09-10T16:27:40.182411Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM_PROGRAM: 
    at yazi-adapter/src/emulator.rs:87

  2024-09-10T16:27:40.182412Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM: xterm-256color
    at yazi-adapter/src/emulator.rs:95

  2024-09-10T16:27:40.192855Z  WARN yazi_adapter::ueberzug: ueberzugpp spawning failed: No such file or directory (os error 2)
    at yazi-adapter/src/ueberzug.rs:96

  2024-09-10T16:27:40.209782Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
    at yazi-adapter/src/emulator.rs:73

  2024-09-10T16:27:40.209788Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM_PROGRAM: 
    at yazi-adapter/src/emulator.rs:87

  2024-09-10T16:27:40.209790Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM: xterm-256color
    at yazi-adapter/src/emulator.rs:95

  2024-09-10T16:27:40.225564Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
    at yazi-adapter/src/emulator.rs:73

  2024-09-10T16:27:40.225567Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM_PROGRAM: 
    at yazi-adapter/src/emulator.rs:87

  2024-09-10T16:27:40.225567Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM: xterm-256color
    at yazi-adapter/src/emulator.rs:95
```
```


### Did you try the latest nightly build to see if the problem got fixed?

No, sorry?

### Describe the bug

If you have a folder open (such as Downloads) the listings will not update if items are added or deleted outside of Yazi.

### Minimal reproducer

CD "move" to a folder such as Downloads or Torrents. When files are completed Yazi will not show as such until you CD "move" elsewhere and come back to the folder for completed Torrents/Downloads.

### Anything else?
I apologize if this is not a bug but rather a misconfiguration.

Yazi does work as intended on my workstation but on my laptop it exhibits the above behavior where folders are not updated.

I had replaced the config toml on the laptop with my functioning one from my workstation and the folder where I first noticed this is a network drive so both machines are watching the same drive (so nothing physical/hardware to the laptop). Laptop is also hardwired.

**Comment by sxyazi** [comment] 2024-09-11 06:49
I can't reproduce it on my macOS and Linux VM.

What file system are you using? Could you record a video showing me your steps in case I missed any details?

**Comment by nPHYN1T3** [comment] 2024-09-11 17:42
Filesystem is EXT4 over NFS mounted with autofs. Again works fine on my workstation too as I said both machines watch the same filesystem/folders for updates. Unless there is some undeclared dependency my workstation has and the laptop doesn't I can't find any errors or discrepancies as to why it works on one and not the other.

Video is a no go for a few reasons but I've uninstalled so don't worry about it. If others aren't experiencing it then it's probably a one off but it does make me think there is something missing. Ye olde works for everyone else (who have kitchen sink KDE/Gnome distros) but super minimal lightweight installs lack some little util it depends on for certain things that wasn't explicitly defined as a dependency. That's just spitballing though.

**Comment by sxyazi** [comment] 2024-09-11 17:58
Alright, let's close the issue then

**Closed by sxyazi** 2024-09-11 17:58 UTC
Labels: bug
