### ISSUE TITLE
upon redraw, keep current hovered file visible

### ISSUE THREAD

**Issue by aidancz** [sxyazi/yazi#1853] opened 2024-10-29 09:22 UTC
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("st-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "xdg-open \"$@\"", block: true, orphan: false, desc: "xdg-open", for_: None, spread: true })
    block  : Some(Opener { run: "xdg-open \"$@\"", block: true, orphan: false, desc: "xdg-open", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/aidan/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

I'm always frustrated when i open a new window, the current hovered file of yazi is invisible

`lf` behaviour:

https://github.com/user-attachments/assets/61bc1e10-9bea-484d-ba48-743b670d6118

`yazi` behaviour:

https://github.com/user-attachments/assets/71aa084c-79eb-4b5b-bc94-cf1592d667ce

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

keep current hovered file visible

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment] 2024-10-29 09:33
> The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

Are you sure the [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't support this feature?

**Comment by aidancz** [comment] 2024-10-29 09:47
Oh, sorry. I didn't clear my own configuration at first (there were incompatible configurations), and mistakenly thought that the latest nightly build did not support this feature.

The latest version works great👍

---

But there is a small problem, the left column will shake


https://github.com/user-attachments/assets/b260a72e-38f6-4310-9906-ff653803f874

**Comment by sxyazi** [comment] 2024-10-29 09:59
This looks like a completely different issue, please file a new issue with the full reproduction steps and complete the bug report template.

I'm going to close this issue since it's a feature that is already supported

**Closed by sxyazi** 2024-10-29 09:59 UTC
Labels: feature
