### ISSUE TITLE
Using shell command did not escape spaces in the path

### ISSUE THREAD

**Issue by 178me** [sxyazi/yazi#1178] opened 2024-06-21 03:14 UTC
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

alacritty 0.13.2 (bb8ea18e)

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

Yazi
    Version: 0.2.5 (Arch Linux 2024-04-27)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: Wayland

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-0")
    DISPLAY: Some(":1")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/zsh")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

### Describe the bug

When I use shell commands to customize shortcut keys

`{ on = [ "D" ],         run = 'shell "trash-put $@" --confirm',       desc = "Permanently delete the files" }`

Cannot execute properly when there are spaces in '$@'

I would like to know how to escape or perform other operations

### Expected Behavior

Able to correctly escape spaces in the path and execute commands

### To Reproduce

{ on = [ "D" ],         run = 'shell "trash-put $@" --confirm',       desc = "Permanently delete the files" }`

**Comment by sxyazi** [comment] 2024-06-21 04:02
You should use `"$@"` instead of `$@` since the latter won't escape special characters in filenames, https://stackoverflow.com/questions/3898665/what-is-in-bash

```
run = '''shell 'trash-put "$@"' --confirm'''
```

Closing as this is expected behavior.

**Closed by sxyazi** 2024-06-21 04:02 UTC
Labels: bug

**Comment by 178me** [comment] 2024-06-21 06:10
> You should use `"$@"` instead of `$@` since the latter won't escape special characters in filenames, https://stackoverflow.com/questions/3898665/what-is-in-bash您应该使用 `"$@"` 而不是 `$@` 因为后者不会转义文件名中的特殊字符，https://stackoverflow.com/questions/3898665/what-is-in-bash
> 
> ```
> run = '''shell 'trash-put "$@"' --confirm'''
> ```
> 
> Closing as this is expected behavior.关闭是预期行为。

So that's the usage, I understand. Thank you
