### ISSUE TITLE
Bulk rename not working if YAZI is called from ZSH keybinding

### ISSUE THREAD

**Issue by uwla** [sxyazi/yazi#1323] opened 2024-07-22 18:07 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (Arch Linux 2024-07-21)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-35
    fzf              : 0.54.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    unar             : 1.10.7
    jq               : 1.7.1

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

It prints the filenames to be renamed but does not renamed them. Here is a demo to illustrate:

![yazi_rename_bug](https://github.com/user-attachments/assets/5abecdb5-037c-473c-b992-d02d5dd6c212)

### Expected Behavior

It should rename files regardless if it is called from `yazi` command or from a keybinding.

### To Reproduce

Here is the ZSH keybinding:

```zsh
_yazi() {
  local tmp
  local cwd
  tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
  	cd -- "$cwd"
  fi
  rm -f -- "$tmp"
  zle reset-prompt;
}

zle -N _yazi
bindkey '^Y' _yazi
```

**Comment by sxyazi** [comment] 2024-07-23 00:35
I can reproduce it, but I'm not sure what the cause is, I *feel* it might be because you registered it as ale using `zle -N`, which changed the behavior of the shell function – why do you need this? 

I myself have bound `Ctrl-y` to launch Yazi too ([here](https://github.com/sxyazi/dotfiles/blob/18ce3eda7792df659cb248d9636b8d7802844831/zsh/function.zsh#L36-L47) and [here](https://github.com/sxyazi/dotfiles/blob/18ce3eda7792df659cb248d9636b8d7802844831/zsh/keymap.zsh#L14)), but I simply used `bindkey -s "^y" "yy\n"`, can you try this to see if it also works for you? Maybe this could serve as a workaround.

**Comment by uwla** [comment] 2024-07-23 12:34
Thanks @sxyazi, it is a good workaround for now.

I was registering with `zle -N` because when I bind the key with `bindkey` I get the following error everytime after exiting `yazi`:

```shell
_yazi:zle:7: widgets can only be called when ZLE is active
```

The workaround works fine, I just think having the error code on exit does not look good

**Comment by sxyazi** [comment] 2024-07-23 13:08
Great to see it works! 

Let's close the issue then because I feel this problem is more like related to the shell's behavior rather than Yazi.

**Closed by sxyazi** 2024-07-23 13:08 UTC
Labels: bug
