### ISSUE TITLE
Feat: Support Sixel image preview with Windows Terminal Preview 1.22.2362.0

### ISSUE THREAD

**Issue by MoaidHathot** [sxyazi/yazi#1571] opened 2024-08-29 21:36 UTC
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.2 (ddb8ce5 2024-08-28)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.2 (ddb8ce5 2024-08-28)

Emulator
    Emulator.via_env: ("", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : None
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "code %*", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block  : Some(Opener { run: "code -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : program not found
    fzf              : 0.52.1
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : program not found
    zoxide           : program not found
    7z               : program not found
    7zz              : program not found
    jq               : 1.7.1
```

### Please describe the problem you're trying to solve

The new Windows Terminal Preview 1.22.2362.0 now support the Sixel format.
Could Yazi use that to preview images?
[Windows Terminal Preview Sixel support release](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-22-release/)

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Yazi to use Sixel format for previewing images when used with Windows Terminal version `1.22.2362.0`+

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment] 2024-08-30 01:26
Duplicate of https://github.com/sxyazi/yazi/issues/1522

**Closed by sxyazi** 2024-08-30 01:26 UTC
Labels: feature
