### ISSUE TITLE
Yazi doesn't update cwd when changing directory

### ISSUE THREAD

**Issue by SolitudeSF** [sxyazi/yazi#2059] opened 2024-12-16 15:25 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.1 (259613b1 2024-12-10)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.80.1 (3f5fd8dd 2024-08-06)

Ya
    Version: 0.4.1 (259613b1 2024-12-10)

Emulator
    Brand.from_env      : Some(Kitty)
    Emulator.detect     : Emulator { kind: Left(Kitty), light: false, cell_size: Some((9, 24)) }
    Emulator.detect_full: Ok(Emulator { kind: Left(Kitty), light: false, cell_size: Some((9, 24)) })

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":1")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: No such file or directory (os error 2)

Variables
    SHELL           : Some("/bedrock/cross/bin/bash")
    EDITOR          : Some("kak")
    VISUAL          : Some("kak")
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.45
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.11.0
    magick        : 7.1.1-41
    fzf           : 0.56.3
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : No such file or directory (os error 2)
    zoxide        : No such file or directory (os error 2)
    7z/7zz        : 24.09 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: 2.2.1 / 2.2.1
    xclip        : 0.13
    xsel         : 1.2.1
```

### Describe the bug

yazi doesn't change its cwd to the current active folder.

### Minimal reproducer

`mkdir t; cd t; yazi`
then go out of that directory and delete it, makes yazi write error messeges to the screen, messing up the rendering.

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by SolitudeSF** [comment] 2024-12-16 15:26
nvm, i cant reporduce it with no config.

**Comment by SolitudeSF** [comment] 2024-12-16 15:43
Okay, the error is from a plugin, but its a symptom of yazi's behavior.

**Comment by SolitudeSF** [comment] 2024-12-16 15:44
but i can workaround that in my specific case...

**Comment by SolitudeSF** [comment] 2024-12-16 15:50
still, its annoying that launching executables from lua, doesnt correctly inherit cwd, unlike `shell` and `open`.

**Comment by SolitudeSF** [comment] 2024-12-16 16:14
Nevermind, you cant workaround that. Launching program from a nonexistant cwd is not possible.

**Comment by sxyazi** [comment] 2024-12-17 00:25
Duplicate of https://github.com/sxyazi/yazi/issues/2042

> - [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried

>     Version: 0.4.1 (259613b1 2024-12-10)

You're not using nightly, 0.4.1 is release version, try latest nightly 0.4.2

**Closed by sxyazi** 2024-12-17 00:25 UTC
Labels: bug
