### ISSUE TITLE
how to support preview of new files ?

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#102] opened 2023-09-01 15:56 UTC
for instance I was navigating a folder with typescript files (*.ts) and yazi 0.1.3 can't preview them ?

I've found no method in the docs (https://github.com/sxyazi/yazi/blob/main/config/docs/yazi.md). By the way I think it would best for the "docs" folder to live at the top-level/root of the repository otherwise it feels like there are no docs

**Comment by sxyazi** [comment] 2023-09-01 16:08
Hey, please take a try for the latest version of Yazi 0.1.4 to see if the issue still exists, and do a `file -bL --mime-type your-ts-file.ts` and paste the output here.

I've put the docs link in README
<img width="834" alt="image" src="https://github.com/sxyazi/yazi/assets/17523360/65a14b6c-0827-41a5-aacd-c7684ee78822">

**Comment by teto** [comment] 2023-09-01 18:27
```
$ file -bL --mime-type vite.config.ts
text/plain
```

**Comment by sxyazi** [comment] 2023-09-01 18:42
Are you using the Nix package to install Yazi? if so you need to add `withFile` to ensure the `file(1)` command is available to Yazi.

**Comment by teto** [comment] 2023-09-01 22:41
yes I am but it's the default anyway https://github.com/NixOS/nixpkgs/blob/421fa98aad6a4028fc090e95199bead30bf669e2/pkgs/applications/file-managers/yazi/default.nix#L9 so it shouldn't be the problem. Also I have `file` in PATH anyway. Let me know how I can help, if there is a way to log more, or just a strace

**Comment by sxyazi** [comment] 2023-09-02 03:51
I added more logs to the `file`, https://github.com/sxyazi/yazi/commit/66aecd54024231ed42a070ad6952f84f36365304

Please use it and do a `cat ~/.local/state/yazi/yazi.log` and paste it here.

**Comment by teto** [comment] 2023-09-02 13:30
the file was created but nothing got logged.

**Comment by sxyazi** [comment] 2023-09-02 14:09
Weird, can you record a GIF, let me know what was happening?

**Comment by teto** [comment] 2023-09-04 15:32
I've added some logging info on the file function and the logging library logs to the file as if it was the terminal.
```
  [2m2023-09-04T13:32:03.224378Z[0m [32m INFO[0m [1;32mcore::external::file[0m[32m: [32moutput of file: "text/plain\napplication/json\ntext/plain\ntext/plain\ntext/plain\ntext/plain\ntext/plain\n"[0m
    [2;3mat[0m core/src/external/file.rs:23

  [2m2023-09-04T13:32:03.226552Z[0m [32m INFO[0m [1;32mcore::external::file[0m[32m: [32moutput of file: "text/plain\napplication/json\ntext/plain\ntext/plain\ntext/plain\ntext/plain\ntext/plain\n"[0m
    [2;3mat[0m core/src/external/file.rs:23
```

I wonder if it's not linked to a timeout issue, this afternoon I could not preview the `cpsell.json` in the yazi directory and right now I can :s

**Comment by sxyazi** [comment] 2023-09-04 16:02
From the logs, it appears that there are no issues. Is this specific to a certain type of file or is it affecting all files? Can it be reproduced?

**Comment by teto** [comment] 2023-09-05 19:05
It looks random, I'll leave this on hold and investigate when I have time.

**Comment by sxyazi** [comment] 2023-09-07 08:24
Due to the inability to consistently reproduce the issue, I'm temporarily closing this issue.

If the issue persists, please reply to this issue, and I will reopen it.

**Closed by sxyazi** 2023-09-07 08:24 UTC
Labels: waiting on op
