### ISSUE TITLE
Cursor blinking in input field can't be disabled 

### ISSUE THREAD

**Issue by yousef8192** [sxyazi/yazi#1343] opened 2024-07-24 21:33 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

terminator 2.1.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####


Yazi
    Version: 0.2.5 (c65a14c 2024-04-23)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/bash")
    EDITOR: Some("vim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.44\nmagic file from /etc/magic:/usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "opener \"$@\"", block: true, orphan: false, desc: "Open", for_: None, spread: true })
    block: Some(Opener { run: "opener \"$@\"", block: true, orphan: false, desc: "Open", for_: None, spread: true })

tmux
    TMUX: true

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/yousef/.local/state/yazi" directory.


```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Sorry but I am not sure whether this is the nightly build or not. Please confirm to me which one is it and I'll for surely try to see if the issue exists in it too.

### Describe the bug

Cursor keeps blinking in input fields even if added "cursor_blink = false" to yazi.toml under the [input] section.

### Expected Behavior

Cursor doesn't blink in input field when "cursor_blink = false" is added to yazi.toml under the [input] section.

### To Reproduce

Add "cursor_blink = false" to yazi.toml and cursor will blink in any input field such as when renaming a file or directory.

**Comment by sxyazi** [comment] 2024-07-24 22:52
> Please confirm to me which one is it and I'll for surely try to see if the issue exists in it too

I can confirm that you are not using the latest code (your build time is `c65a14c 2024-04-23`). 

`cursor_blink = false` is a feature that was recently added and is currently only available on the latest main branch. You can build it by following https://yazi-rs.github.io/docs/installation#cargo or https://yazi-rs.github.io/docs/installation#build-from-source, or you can wait for the next release, which should be out this week.

I'm going to close this issue since it's not a bug.

**Closed by sxyazi** 2024-07-24 22:52 UTC
Labels: bug

**Comment by yousef8192** [comment] 2024-07-25 01:21
Thanks for the clarification
