### ISSUE TITLE
Automatically activate direnv upon entering directory

### ISSUE THREAD

**Issue by noggynoggy** [sxyazi/yazi#1693] opened 2024-09-27 12:15 UTC
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (70fbe41 2024-09-27)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (70fbe41 2024-09-27)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("918d8340afd652b011b937d29d5eea0be08467f5_1727434818_654492852")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/run/current-system/sw/bin/bash")
    EDITOR             : Some("hx")
    VISUAL             : Some("hx")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "helix", for_: None, spread: true })
    block  : Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "helix", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-35
    fzf              : 0.54.2
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : 24.07
    jq               : 1.7.1
```

### Please describe the problem you're trying to solve

I am using `direnv` + `nix-direnv` to enter nix-shells for development. When I `cd` (or `z`) into a projects directory, direnv automatically activates (e.g. setting variables). But when I enter a directory in `yazi` (via `l` or via `z`), `direnv` only launches if I quit `yazi`  there. If I launch my editor from `yazi` without exiting in the directory and re-entering `yazi`, my editor is then also missing the variables.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Activate the `.envrc` upon entering a directory

### Additional context

Complex Nix shells can take time to create, so it is probably best to design it as a task, instead of blocking `yazi` for the time.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment] 2024-09-27 14:17
Duplicate of https://github.com/sxyazi/yazi/discussions/1083

**Closed by sxyazi** 2024-09-27 14:17 UTC
Labels: feature
