### ISSUE TITLE
Show current directory size

### ISSUE THREAD

**Issue by og900aero** [sxyazi/yazi#1569] opened 2024-08-29 11:36 UTC
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.2 (b280d79 2024-08-29)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0 (c75960e 2024-08-14)

Emulator
    Emulator.via_env: ("st-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("micro")
    VISUAL             : Some("micro")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.3a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.44
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : No such file or directory (os error 2)
    fzf              : 0.50.0
    fd               : No such file or directory (os error 2)
    rg               : 13.0.0
    chafa            : 1.12.4
    zoxide           : 0.4.3
    7z               : No such file or directory (os error 2)
    7zz              : 22.01
    jq               : 1.6

```

### Please describe the problem you're trying to solve

Show the size of the current directory.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

When I press whatever keybinding, then show the size of the current directory.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment] 2024-08-29 17:22
Duplicate of https://github.com/sxyazi/yazi/issues/842, please search before filing a new issue.

I haven't had time to implement it yet, if you need an immediate solution, use the https://github.com/pirafrank/what-size.yazi plugin

Closing as duplicate

**Closed by sxyazi** 2024-08-29 17:22 UTC
Labels: feature

**Comment by og900aero** [comment] 2024-08-30 06:08
> Duplicate of #842, please search before filing a new issue.
> 
> I haven't had time to implement it yet, if you need an immediate solution, use the https://github.com/pirafrank/what-size.yazi plugin
> 
> Closing as duplicate

None of the solutions you outlined can be used correctly, because it either shows the size in a pop-up window, or in the part above where it shows the current path.
The normal solution would be to put it in the linemode section, so that each retrieved size would remain visible, and it would be possible to calculate how big the total size would be if I wanted to copy or move to the usb drive, or network drive or another partition and I calculated about free space.

**Comment by sxyazi** [comment] 2024-08-30 06:22
> The normal solution would be to put it in the linemode section

Yep this is the goal that PR wants to achieve
