### ISSUE TITLE
Cutting and pasting a file back into it's same original directory still appends  _1 suffix

### ISSUE THREAD

**Issue by newinput** [sxyazi/yazi#1834] opened 2024-10-25 18:23 UTC
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty v0.36.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (56f9a6a 2024-10-25)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("<redacted>")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/fish")
    EDITOR             : Some("/home/username/bin")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.10.3
    zoxide           : No such file or directory (os error 2)
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/username/.local/state/yazi" directory.
```

### Describe the bug

When you `cut (x)` and `paste (p)` a file in it's same original directory, it has a duplicate filename conflict with itself and adds a `_1` suffix to the filename before moving itself back to the same place. 

### Minimal reproducer

eg. 
Cutting `my_dir/a.txt`  and pasting  it in the same `my_dir/` gives `my_dir/a_1.txt`  instead of not moving the file. 

### Anything else?

**no custom configs used** 
Haven't added any custom configs to yazi, just used as is after building from source.

-----

Also thanks for the very cool project here,  and apologies if the issue is written a little rough as I haven't submitted one before. 

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment] 2024-10-28 04:27
Duplicate of https://github.com/sxyazi/yazi/issues/330

**Closed by sxyazi** 2024-10-28 04:27 UTC
Labels: bug

**Comment by newinput** [comment] 2024-10-28 05:30
> Duplicate of #330

Oh no I'm sorry, I must have forgotten to remove the automatic is:open filter when I searched for any duplicates.
