### ISSUE TITLE
`Command palette` to launch commands without assigning keyboard hotkey

### ISSUE THREAD

**Issue by VKondakoff** [sxyazi/yazi#1211] opened 2024-06-25 12:19 UTC
### Please describe the problem you're trying to solve

Currently the only way to launch commands in yazi is to assign a dedicated keyboard hotkey to specified command. But available hotkeys are limited. Look at the [plugins](https://github.com/yazi-rs/plugins): the `max-preview` and `hide-preview` are recommending the same hotkey (`t`) and the `jump-to-char` is recommending `f` which is assigned to Find command.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

So, I'm sure there is a need of something like `command palette` to run commands without any hotkey, just by choosing them from the list.  (Fuzzy) search within commands is highly welcome.

### Additional context

Just for an example: command palette in Obsidian:

<img width="951" alt="Снимок экрана 2024-06-25 в 15 17 36" src="https://github.com/sxyazi/yazi/assets/230824/857f98d6-4f8a-4441-b427-de177c9d6411">

**Comment by sxyazi** [comment] 2024-06-25 12:42
Duplicate of https://github.com/sxyazi/yazi/issues/1153

**Closed by sxyazi** 2024-06-25 12:42 UTC
Labels: feature
