### ISSUE TITLE
Escape find only if find is active in the current directory.

### ISSUE THREAD

**Issue by amano-kenji** [sxyazi/yazi#1825] opened 2024-10-23 23:42 UTC
### Please describe the problem you're trying to solve

escape_find escapes find even if find is not active in the current directory.

This means if I find a directory, enter it, select some files with space key, and then press esc, inactive/invisible find is escaped before selection is escaped.

It is confusing because find is inactive or invisible.

### Describe the solution you'd like

Find should be escaped only when it is active or visible. Filter is not escaped when it is not visible or active in the current directory. Thus, filter is intuitive. Find is not intuitive, yet. This will improve intuitiveness of escape hugely.

Yazi is trying to have sane defaults. I think this is the sane default behavior.

**Comment by sxyazi** [comment] 2024-10-23 23:50
Duplicate of https://github.com/sxyazi/yazi/discussions/1768, please don't create duplicate posts.

I've noticed all the posts you've made, just I need once I find a moment to calm down and think it through then I'll reply to them all, closing as duplicate

**Comment by amano-kenji** [comment] 2024-10-23 23:51
https://github.com/sxyazi/yazi/discussions/1768 described the problem, and this issue is my proposed solution.

**Comment by sxyazi** [comment] 2024-10-23 23:54
You should mention it in this issue. 

Anyway, let's reopen this issue and close that discussion since we just need one post to keep track of the same thing.

**Comment by amano-kenji** [comment] 2024-10-24 00:00
An idea is to escape find only when it is visible in the current directory. So, if it is active but invisible in the current directory, find is not escaped.

Escaping invisible find is not intuitive.

Another idea is to indicate that find is active (in the current directory or any other directory) in the UI, but this will consume valuable space in the UI.

I think find should be visible in some way when find is escaped.

**Comment by sxyazi** [comment] 2024-10-24 03:43
> Filter is not escaped when it is not visible

The question here is: how do you define "visible"? If you have a directory with 1,000 files and you're currently looking at the top 1~30 files, but the highlight is indeed applied to the 999th file, it's clear that the 999th file isn't visible, yet it's still a valid match. So when you press `Esc`, how should that be handled? Should the valid match be cleared as well? Or do you only consider files invisible if none of all 1,000 files match?

**Comment by amano-kenji** [comment] 2024-10-24 04:14
Visible files are visible in the rendered view. They are visible to the user.

If yazi can efficiently calculate visible files, then it can escape only find visible to the user.

Or, you can display a small find indicator somewhere in the UI.

**Comment by sxyazi** [comment] 2024-10-24 04:35
> Visible files are visible in the rendered view

I don't think this makes sense because it ties the user's Esc behavior to their scrolling position in the file list. This means that Esc will act differently depending on where the user is in the list — whether they're in the "visible area" with matches or in the non-visible area.

**Comment by boydaihungst** [comment] 2024-10-24 05:02
Just create a plugin uses dds sub the "cd" event, then run clear find or filter if you go back to parent folder? That make sense, when you find/filter something in child folder, then moving back to parent folder (but not if you go to grandchild folder). The preview tab won't show “No items”. Imagine you leave yazi for hours, then come back and see your precious folder showing “No items” in preview tab...

**Comment by sxyazi** [comment] 2024-10-24 05:13
I'm confused. Are you saying you want to implement it for "find" or "filter", or them both? They are two completely different features. 

The description of this issue is also pretty vague — it talks about "escape_find", but, the "filter" also keeps showing up.

![screenshot-002079](https://github.com/user-attachments/assets/84eb3cc9-36a3-4fe6-8979-c32edf5457d2)

**Comment by boydaihungst** [comment] 2024-10-24 05:23
I think he want to show an indicator for find command in the header after cwd path (just like filter `filter: text`). So that when he press `escape` the indicator gone, and find is clear. If he have 1000 items, and the find results item are all out of view (isn't rendered), press should clear find, hide indicator first before clear selected items.

**Comment by sxyazi** [comment] 2024-10-24 05:33
I agree, this would be a simpler and more intuitive way

**Comment by amano-kenji** [comment] 2024-10-24 07:00
I think something like this can make sense.

[3][2] or [F][2]

3 means the number of found items. `F` is merely an indicator for find. 2 is the number of selected items.

This is small, and doesn't take a lot of space.

**Closed** 2024-10-28 09:14 UTC
Labels: feature
