### ISSUE TITLE
Image prevew works, but the output position is wrong - tiny bottom right corner (Windows, WSL2, Ubuntu 24.04,  Wezterm)

### ISSUE THREAD

**Issue by Igonato** [sxyazi/yazi#1579] opened 2024-08-31 14:55 UTC
### What system are you running Yazi on?

Windows WSL

### What terminal are you running Yazi in?

Wezterm

### `yazi --debug` output

```Shell
^[P>|WezTerm 20240203-110809-5046fc22^[\
Yazi
    Version: 0.3.2 (907ac09 2024-08-31)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.2 (907ac09 2024-08-31)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: true

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.44.1
    fd               : 10.2.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 23.01
    7zz              : No such file or directory (os error 2)
    jq               : 1.7


~/.local/state/yazi/yazi.log:

  2024-08-31T14:47:02.475991Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
    at yazi-adapter/src/emulator.rs:70

  2024-08-31T14:47:10.889541Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
    at yazi-adapter/src/emulator.rs:70

  2024-08-31T14:47:10.892866Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
    at yazi-adapter/src/emulator.rs:70

  2024-08-31T14:47:10.892890Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
    at yazi-adapter/src/emulator.rs:70
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Image preview seems to work but the output is stuck in the tiny region in the bottom right corner:

https://github.com/user-attachments/assets/6f5416cf-8669-42d3-a753-8f5a4db116f0

### Minimal reproducer

Installed via `cargo install --locked --git https://github.com/sxyazi/yazi.git yazi-fm yazi-cli`
With dependencies installation I went fast and loose w/o taking notes on how I got each, but mostly it's was either through `apt install` or built from source.

### Anything else?

Outside of WSL images work flawlessly 👍

**Comment by sxyazi** [comment] 2024-08-31 17:37
Duplicate of https://github.com/sxyazi/yazi/issues/712

This is ConPTY interfering between the terminal and Yazi; you need to use `wezterm ssh`, see docs at https://yazi-rs.github.io/docs/image-preview#wsl

**Closed by sxyazi** 2024-08-31 17:37 UTC
Labels: bug
