### ISSUE TITLE
[Lua] unable to import

### ISSUE THREAD

**Issue by f3fora** [sxyazi/yazi#1811] opened 2024-10-19 19:43 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("/usr/bin/vi")
    VISUAL             : Some("/usr/bin/vi")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

Unable to import package or module in any lua file.

As an example I report a plugin `ab.yazi`, which try to include a package under the same directory. 
Of course, the packages installed system-wide are not available either.

Printing `package.path` and `package.cpath` shows an acceptable result, i,e, the path includes the wanted string. Thus, I have no idea why it doesn't work.

### Minimal reproducer

```
 .
├──  flavors
├──  keymap.toml
├──  package.toml
├──  plugins
│  └──  ab.yazi
│     ├──  cd.lua
│     └──  init.lua
├──  theme.toml
└──  yazi.toml
```

```lua
-- init.lua
local cd = require("cd")
return {
  event = {
    ya.notify(cd)
  },
}
```

```lua
-- cd.lua
return {
  title = "12",
  content = "12",
  level = "error",
  timeout = 12,
}
```

```toml
# keymap.toml
[[manager.prepend_keymap]]
on   = [";", "a", "b"]
run  = 'plugin ab'
desc = "ab plugin"
```

### Anything else?

I haven't try nightly since the version bump happened very recently and there is no commit that seems to address this issue.

**Comment by sxyazi** [comment] 2024-10-20 03:51
This is by design - `require()` is used to import a Yazi module, which is a directory structured as described in https://yazi-rs.github.io/docs/plugins/overview. If you [inspect](https://yazi-rs.github.io/docs/configuration/keymap/#tasks.inspect) the logs, you'll find an error like: 

```
failed to load plugin from "/Users/test/.config/yazi/plugins/cd.yazi/init.lua"
stack traceback:
	[C]: in local 'poll'
	[string "?"]:4: in function 'require'
	[string "test"]:3: in function <[string "test"]:2>
```

This means that you need to place the `cd.lua` as a directory in the `plugins` directory.

If you really want to import a single file from the current directory, use `dofile()`:

```lua
local cd = dofile("./cd.lua")
ya.err(cd)
```

Doc : https://www.lua.org/manual/5.4/manual.html#pdf-dofile

Closing as it's expected behavior

**Closed by sxyazi** 2024-10-20 03:51 UTC
Labels: bug

**Comment by f3fora** [comment] 2024-10-20 09:28
What if I want to use a package from Luarocks?

**Comment by sxyazi** [comment] 2024-10-20 16:08
Can you be more specific? What kind of Luarocks package do you want to use? 

Generally, if the package offers common functionality, I'll include it in the Yazi API, as this provides better performance than including external Lua files. 

Yazi creates a separate Lua runtime for each async plugin, so it's assumed that user plugins won't be too large. If a plugin is big enough, it likely means it's complex, and I usually recommend breaking it into two independent plugins with full functionalities.

**Comment by f3fora** [comment] 2024-10-20 17:14
My idea was to use [lgi](https://github.com/lgi-devs/lgi) to access [udisks2 API](https://storaged.org/doc/udisks2-api/latest/) to manage external resources. 

See #927

**Comment by sxyazi** [comment] 2024-10-25 01:19
Why not just use the [`udisksctl` command-line tool](https://storaged.org/doc/udisks2-api/latest/udisksctl.1.html)? It's simpler and more convenient than introducing a Luarocks package. 

Users don't need to install it through Luarocks and compile any C code, and their systems probably already have `udisksctl` — I just tested it, and it's available in my freshly installed Manjaro VM.

You can use the `Command` API provided by Yazi to call it: https://yazi-rs.github.io/docs/plugins/utils#command, and Ranger's [ranger_udisk_menu](https://github.com/SL-RU/ranger_udisk_menu) plugin is a great example you can reference to

**Comment by f3fora** [comment] 2024-10-25 07:50
From [udisksctl man](https://storaged.org/doc/udisks2-api/latest/udisksctl.1.html):

> This program does not assume that the caller is the super user - it is intended to be used by unprivileged users and authorizations are checked by the udisks daemon using polkit(8). Additionally, this program is not intended to be used by scripts or other programs - options/commands may change in incompatible ways in the future even in maintenance releases. See the “API STABILITY” section of [udisks(8)](https://storaged.org/doc/udisks2-api/latest/udisks.8.html) for more information.

Eventually, one can install `lua-lgi` if you are in Arch-based distribution, without needing luarocks.

**Comment by sxyazi** [comment] 2024-11-03 11:52
Ah that's true. It seems that https://github.com/SL-RU/ranger_udisk_menu uses `lsblk` and `udisks2` together, since `lsblk` is also mentioned in the README. Is this approach feasible?

Getting Yazi to support Luarocks might not be easy because [Yazi's `require()`](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/src/loader/require.rs) isn't a standard Lua function. 

Instead, the imported modules are returned as a wrapper table to keep track of the currently running modules, which is necessary for [supporting `ya.sync()`](https://yazi-rs.github.io/docs/plugins/overview#async-context). But I haven't actually used Luarocks myself, I could be wrong.

Also, Yazi uses the latest Lua 5.4, which doesn't have a [`ffi` module](https://luajit.org/ext_ffi.html) like Luajit. Are you sure that `udisks2` supports Lua 5.4?

**Comment by sxyazi** [comment] 2025-01-26 18:00
Made a plugin for this, https://github.com/yazi-rs/plugins/tree/main/mount.yazi
