### ISSUE TITLE
Feat: winget package

### ISSUE THREAD

**Issue by patrick-5546** [sxyazi/yazi#1088] opened 2024-05-26 01:53 UTC
### Please describe the problem you're trying to solve

Currently the only windows package manager can install yazi is scoop

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It would be convenient to be able to install yazi using winget

**Comment by sxyazi** [comment] 2024-05-26 10:10
Nice to have! 

Does anyone want to submit a winget package for Yazi?

**Comment by MoaidHathot** [comment] 2024-06-25 07:53
Hi @sxyazi, I went ahead and submitted the first Manifest for Yazi. Could you please take a look on the values and make sure they are ok with you?
After that Manifest is approved and merged into Winget's package repo, I'll submit a PR adding this step into the CI/CD; we have to create the first one manually first.

**Comment by sxyazi** [comment] 2024-06-25 09:49
Yeah sure, thank you @MoaidHathot!

**Comment by MoaidHathot** [comment] 2024-06-26 23:33
@sxyazi, in the meanwhile while we are waiting for the Winget Manifest to be  merged, I think there are two things I need help with in order to setup the CI for this :)
According to the `Winget Releases` task we need the following:
* Classic Personal Access Token (PAT) with `public_repo` scope. Could you pleas store it in a variable so we could access it via the CI?
* Fork ![microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account of this repository.

**Comment by sxyazi** [comment] 2024-06-27 12:13
> Could you pleas store it in a variable so we could access it via the CI?

Done, variable name `WINGET_TOKEN`

> Fork microsoft/winget-pkgs under the same account of this repository.

Done!

**Comment by MoaidHathot** [comment] 2024-06-27 15:33
Thanks!
I will issue a PR for automating the release :)

**Comment by Daydreamer-riri** [comment] 2024-07-10 13:11
‌‌Hi @MoaidHathot, the current winget PR has been closed. Can we check what the situation is?

**Comment by MoaidHathot** [comment] 2024-07-13 05:10
Hi @Daydreamer-riri, @sxyazi, I have created a new PR for `winget-pkgs` instead of the one that they have closed.
https://github.com/microsoft/winget-pkgs/pull/162792

The issue was with the wrong architecture of `Microsoft.VCRedist.2015`. I was able to reproduce then fix and validate the issue via `Windows Sandbox`.
Since both `Microsoft.VCRedist.2015+.x64` and `Microsoft.VCRedist.2015+.x86` are probably installed on many Windows machine, `Windows Sandbox` was necessary to make sure there isn't a hidden or already installed dependency.

**Comment by MoaidHathot** [comment] 2024-07-14 22:13
@sxyazi, @Daydreamer-riri, the PR has been merged into `winget-pkgs` and `Yazi` is now consumable via `winget`.
I'll create a PR for this repo for publishing new versions into `winget` upon new releases from CI/CD.

![image](https://github.com/user-attachments/assets/adbc0e26-d2e0-4c5b-a5b4-278a51b84cd9)

**Comment by Daydreamer-riri** [comment] 2024-07-15 00:59
Awesome! Thanks for the work!

**Comment by sxyazi** [comment] 2024-07-15 08:14
Nice work @MoaidHathot, thank you! 

Hey @patrick-5546, Yazi is now on `winget`, please have a look, I think we can end this issue now.

**Closed by sxyazi** 2024-07-15 08:14 UTC
Labels: help wanted, good first issue, feature

**Comment by MoaidHathot** [comment] 2024-07-16 05:07
I have created the following PR https://github.com/sxyazi/yazi/pull/1299
