### ISSUE TITLE
VSCode integrated terminal image preview distorted

### ISSUE THREAD

**Issue by baitian752** [sxyazi/yazi#446] opened 2023-12-11 10:51 UTC
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

VSCode integrated terminal (VSCode 1.85.0)

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Remote SSH for my linux server

Run `yazi`
![image](https://github.com/sxyazi/yazi/assets/28034106/ffea5c85-8bce-4fa8-9155-ce10f24ab697)

View the first image (1024x1024, OK)
![image](https://github.com/sxyazi/yazi/assets/28034106/d77dcb69-5fa3-4edb-89bd-ce80996c96e3)

Back to the text file (there is an image border)
![image](https://github.com/sxyazi/yazi/assets/28034106/c85413ae-2029-4484-b02e-7379d9c7bda2)

View the second image (1024x1536 distorted)
![image](https://github.com/sxyazi/yazi/assets/28034106/c245c624-3327-4688-9b0e-b0db986cf0c0)

The original image:
![04_04](https://github.com/sxyazi/yazi/assets/28034106/c8cd2190-4c13-4bc4-a6ef-ce00278d7749)

### Expected Behavior

Preview is OK.

### To Reproduce

As the bug description.

**Comment by baitian752** [comment] 2023-12-11 11:05
After some tests, I found this issue is relative to the global zoom level of VSCode, but the color is not correct at zoom level 0.

![image](https://github.com/sxyazi/yazi/assets/28034106/942fdc51-4121-46df-bb06-4bad9f362433)

**Comment by sxyazi** [comment] 2023-12-11 14:45
Try reducing [`max_width` and `max_height`](https://yazi-rs.github.io/docs/configuration/yazi#preview) to see if the issue still exists - Yazi cannot obtain the correct terminal pixel width and height for displaying images due to `VSCode` not implementing the `ioctl(TIOCGWINSZ)` system call. Therefore, fixed `max_width` and `max_height` are currently used. The issue you're describing is caused by images exceeding the available area and resulting in scrolling.

Another way to obtain pixel width and height is through `CSI 14 t`, but unfortunately, `crossterm` does not provide any way for users to extend it; it can only be added to the `crossterm` codebase. I've submitted a patch, but it hasn't been merged yet, https://github.com/crossterm-rs/crossterm/pull/810. So, currently, in `VSCode`, you can only limit the image size using `max_width` and `max_height` instead of dynamically adjusting based on terminal size.

As for image colors, this is the expected behavior. Currently, `VSCode` only supports `Sixel graphics protocol`, which is a rather old protocol that only supports `256` colors. So Yazi can only use approximate colors as substitute colors for display. Until `VSCode` supports more advanced protocols (such as [Terminal graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol) or [Inline images protocol](https://iterm2.com/documentation-images.html) protocols), it cannot be improved.

**Comment by baitian752** [comment] 2023-12-12 01:49
Thanks for you information. And for the colors, I have also test `imgcat`, which looks OK:

![image](https://github.com/sxyazi/yazi/assets/28034106/d35d387f-986e-4eed-aa2f-36962964663a)

**Comment by baitian752** [comment] 2023-12-12 03:24
I have tried set preview size with `max_width` and `max_height`. It looks good, thank you.

![image](https://github.com/sxyazi/yazi/assets/28034106/0785544e-30c5-4350-a54b-7b33a0075215)

**Comment by sxyazi** [comment] 2023-12-27 07:28
> Thanks for you information. And for the colors, I have also test imgcat, which looks OK:

I think this is not a bug, it's just that Yazi's default image compression strategy is more aggressive.

I'll add a new config option to allow users to adjust the compression level manually.

**Closed** 2024-01-25 07:48 UTC
Labels: enhancement
