### ISSUE TITLE
Powershell "y" alias decoding error.

### ISSUE THREAD

**Issue by Aqaao** [sxyazi/yazi#1921] opened 2024-11-19 11:33 UTC
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm

### `yazi --debug` output

```Shell
None
```

### Describe the bug

Windows powershell Chinese character decoding error when use "y" command.

### Minimal reproducer

start yazi via "y" alias, select a path that contains Chinese characters, then press "q" quit yazi. 
![图片](https://github.com/user-attachments/assets/63494e5c-5fa4-4e54-9d4e-961802e41e02)
![图片](https://github.com/user-attachments/assets/92d3fe48-a6d2-4df0-9813-3a93a4e62053)

### Anything else?

Resolved via add `-Encoding UTF8` arg to Powershell wrapper function's line 4.
``` powershell
$cwd = Get-Content -Path $tmp  -Encoding UTF8 
```

Maybe docs should be modified to add this arg ?

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment] 2024-11-19 11:59
I have no idea of how those PowerShell things work, so as usual, I'd like somebody else to confirm this is OK

---

Pinging @luiz00martins, sorry to bother you, but can you please confirm if `-Encoding UTF8` is OK, since you're the original author of the PowerShell wrapper ;)

**Comment by Xerxes-2** [comment] 2024-11-21 03:40
Can you reproduce it in PowerShell 7+?

**Comment by Aqaao** [comment] 2024-11-21 05:18
> Can you reproduce it in PowerShell 7+?

I installed PowerShell 7 , it does not have this issue, error only occurs in the pre-installed PowerShell 5.

**Comment by sxyazi** [comment] 2024-11-22 04:47
Moved to https://github.com/yazi-rs/yazi-rs.github.io/issues/170 as it's an error with the doc not Yazi itself

Closing in favor of that issue

**Closed by sxyazi** 2024-11-22 04:47 UTC
Labels: bug, help wanted
