### ISSUE TITLE
Audio distortion when resizing yazi window and using a pipewire max-quantum of < 128.

### ISSUE THREAD

**Issue by ThGrSoRu** [sxyazi/yazi#789] opened 2024-03-07 14:02 UTC
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot version: 1.16.2 +pgo +ime +graphemes -assertions

### Yazi version

yazi 0.2.3 (1aed6e8 2024-03-06)

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

When playing audio, opening a directory in yazi with more than ~10 (video) files and resizing the window causes audio distortion.
Distortion is more intense if the files are video files.
Also happens during preloading of files.
Happens in Hyprland `77161fdb` and sway `59f6292`.

Does not happen when resizing other application windows.
Disabling sixel previews or changing the amount of micro/macro workers shows no change.

### Expected Behavior

No distortion when resizing a yazi window.

### To Reproduce

See above.

**Comment by ThGrSoRu** [comment] 2024-03-07 17:42
It seems this happens generally under IO loads.

**Comment by sxyazi** [comment] 2024-03-29 10:05
I'm not quite sure what's causing it, and it seems like you've tried everything I can think of (disabling previews, reducing workers), so I'm not sure what else I can do here.

Have you tried other terminals to see if the issue occurs during resize? And does it only happen in pipewire - seems it's a video player?

**Comment by ThGrSoRu** [comment] 2024-03-29 11:03
[Pipewire](https://pipewire.org/) is a server for handling audio and video streams, it intends to replace [PulseAudio](https://www.freedesktop.org/wiki/Software/PulseAudio/) and [Jack](https://jackaudio.org/).
It's Linux and FreeBSD only.
On the Alacritty terminal, which does not support Sixel previews, there is no distortion when resizing the terminal window.
However, when preloading new files there is distortion on foot **and** Alacritty.

**Comment by sxyazi** [comment] 2024-03-29 11:35
Can you try disabling all preloader and previewer plugins one by one to see if that resolves the issue? If this is related to I/O, then besides reading the file list, only the previewer and preloader involve I/O operations. And have you tried reducing the number of workers to a minimum of 1?

**Comment by ThGrSoRu** [comment] 2024-03-29 12:08
Both preloaders and previewers cause distortion.
Setting both macro and micro workers to 1 and/or using PulseAudio, the distortion still appears.

**Comment by sxyazi** [comment] 2024-03-29 12:18
Do you mean that as long as any one of those previewers/preloaders is turned on it causes distortion, but if you disable all of them, there won't be distortion right?

**Comment by ThGrSoRu** [comment] 2024-03-29 12:24
I tried doing `{name="*",run="noop"}`, `=[]`, removing the plugins folder from the config directory, but yazi still runs some preloaders.

**Comment by sxyazi** [comment] 2024-03-29 12:27
Try this:

```toml
# yazi.toml

[tasks]
micro_workers = 1
macro_workers = 1

[plugin]
preloaders = []
previewers = []
```

**Comment by ThGrSoRu** [comment] 2024-03-29 12:32
I misspelled the plugin section as plugin**s**. Now it doesnt load any preloaders or previewers, and there is no distortion now.

**Comment by sxyazi** [comment] 2024-03-29 12:40
Can you test them individually and narrow down the issue? For example, first determine if the issue is caused by preloaders or previewers, and whether setting micro_workers = 1, macro_workers = 1 has any effect.

**Comment by ThGrSoRu** [comment] 2024-03-29 12:56
Changing worker amounts does not reduce or remove distortion.
Distortion does not occur when disabling image and video preloaders and previewers.
Other preloaders and previewers, like pdf or audio only cause slight distortion.

**Comment by sxyazi** [comment] 2024-03-29 13:15
Then try directly calling `pdftoppm` to generate the PDF preview and see if the problem still. Here is the command:

https://github.com/sxyazi/yazi/blob/66d12da09dd813efb57627bb9af08b9444cc5800/yazi-plugin/preset/plugins/pdf.lua#L29-L33

**Comment by sxyazi** [comment] 2024-03-29 13:58
Hmm I don't think this is an issue specific to Yazi, as Yazi essentially does the same thing as those external programs (ffmpegthumbnailer, poppler, etc.), which is to read files and then generate previews - since the file sizes are the same, there won't be any difference in the I/O read.

I'm curious about why pipewire would distort due to I/O reading, this sounds like a bug, do other programs have this issue?

However, if using external programs reduces this issue, you may consider using this plugin: https://github.com/Sonico98/allmytoes.yazi, it generates thumbnails for videos and images using [allmytoes](https://gitlab.com/allmytoes/allmytoes).

Closing as not Yazi

**Closed by sxyazi** 2024-03-29 13:58 UTC
Labels: bug
