### ISSUE TITLE
Top status with path and tabs not shown, unable to create now tabs.

### ISSUE THREAD

**Issue by MattiaSilvestri** [sxyazi/yazi#1623] opened 2024-09-09 09:33 UTC
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.36.1

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (9483798 2024-09-08)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (9483798 2024-09-08)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("118d4e1001d5847aa42d1e5d5fa9623954ae751d_1725862076_19435265")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.5
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.54.3
    fd               : 10.2.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

The place at the top of the window where the current path and tabs used to be shown si now empty, and if I press `t` to create a new tab nothing happens.

### Minimal reproducer

Difficult to provide a reproducer, I probably just did an update from the previous to last version of yazi and the top status disappeared: no more path and tabs shown at the top of the window.
I'm sorry to not be able to provide more info but I don't seem to recall doing anything special for this beahvior to appear, I realised this thing after I while so I'm not able to exactly pinpoint the moment when this happened.

**Comment by sxyazi** [comment] 2024-09-09 09:54
If there's no minimal reproduction, it's hard for me to say what the issue is. 

My best guess is that this is caused by your config, you can try disabling all custom configs (`mv ~/.config/yazi ~/.config/yazi.bak`) to see if the issue still.

**Comment by MattiaSilvestri** [comment] 2024-09-09 17:54
Yeah, I had in a few lines of code in the init.lua that apparentty didn't work well with the new updates:
```
function Header:render(area)
	self.area = area

	local right = ui.Line({ self:count(), self:tabs() })
	local left = ui.Line({
		self:host(),
		self:cwd(math.max(0, area.w - right:width())):fg("blue"),
		ui.Span("/"):fg("blue"):bold(true),
		ui.Span(tostring(cx.active.current.hovered.name)):fg("white"):bold(true),
	})
	return {
		ui.Paragraph(area, { left }),
		ui.Paragraph(area, { right }):align(ui.Paragraph.RIGHT),
	}
end
```
I'm not the author of this code, but removing it solved the issue. I completely forgot it was there, thanks for the quick reply anyway.

**Comment by sxyazi** [comment] 2024-09-10 04:05
Nice to see the problem solved! Let's close this issue then

**Closed by sxyazi** 2024-09-10 04:05 UTC
Labels: invalid
