### ISSUE TITLE
Screen goes blank when using open command in Windows Terminal

### ISSUE THREAD

**Issue by tayopi** [sxyazi/yazi#1733] opened 2024-10-04 22:49 UTC
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Windows Terminal - Version: 1.21.2701.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (3321f47 2024-10-04)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.3 (3321f47 2024-10-04)

Emulator
    Emulator.via_env: ("", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Microsoft

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : None
    EDITOR             : Some("micro")
    VISUAL             : None
    YAZI_FILE_ONE      : Some("C:\\\\Program Files\\\\Git\\usr\\\\bin\\\\file.exe")
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "micro %*", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block  : Some(Opener { run: "micro -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : program not found
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : program not found
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : 24.08
    7zz              : program not found
    jq               : program not found
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Whenever I press <Enter> or o to open a file or folder my terminal goes blank. I have tried this in multiple shells including PowerShell, Nushell, and Bash. I can press the navigation keys and some elements return, but not everything.

### Minimal reproducer

1. Open Windows Terminal.
2. Start yazi
3. Press <Enter> or o to execute open command.
4. Terminal goes blank
5. Press <Left> or h to execute leave command.
6. Some elements of yazi are written to the terminal.

## PowerShell
Before executing open command:
![image](https://github.com/user-attachments/assets/46c89788-d330-4ec7-a24b-43edf668493b)

After executing open command:
![image](https://github.com/user-attachments/assets/a8c95412-f375-491e-8374-db14d2fce5e0)

After executing leave command:
![image](https://github.com/user-attachments/assets/0343b5f3-8d84-40b9-96f3-d5d38abc6f9a)

## Nushell
Before executing open command:
![image](https://github.com/user-attachments/assets/5005eac4-029c-4588-8532-abe615ca61fc)

After executing open command:
![image](https://github.com/user-attachments/assets/7623c87f-0543-49a5-8177-36be2fa8a420)

After executing leave command:
![image](https://github.com/user-attachments/assets/688e0579-73d9-48af-8e6e-796ee8adb3b3)

## Bash
Before executing open command:
![image](https://github.com/user-attachments/assets/4addfe76-3300-499f-9826-f439f6ded363)

After executing open command:
![image](https://github.com/user-attachments/assets/a1e50572-a624-4a87-acf6-a6493f6af50d)

After executing leave command:
![image](https://github.com/user-attachments/assets/d844ae7a-cf8a-4286-a5cb-7601730746fa)

**Comment by sxyazi** [comment] 2024-10-05 05:06
I can't reproduce it on my Windows VM.

Did you use any custom configs/plugins? Can you reproduce it with the default config (`mv C:\Users\USERNAME\AppData\Roaming\yazi C:\Users\USERNAME\AppData\Roaming\yazi-backup`)? What's your opener for dirs? Does it work when you run it directly without Yazi in your terminal?

Let me know if I missed any details for replicating it.

**Comment by tayopi** [comment] 2024-10-07 23:13
> Did you use any custom configs/plugins?

No.

> Can you reproduce it with the default config (mv C:\Users\USERNAME\AppData\Roaming\yazi C:\Users\USERNAME\AppData\Roaming\yazi-backup)?

I cannot reproduce the issue with the default config. With the default config, the open command opens everything in Visual Studio Code.

> What's your opener for dirs?

I'm not sure how to determine that.

> Does it work when you run it directly without Yazi in your terminal?

Does what work? I'm afraid I don't understand the question.

**Comment by sxyazi** [comment] 2024-10-08 03:09
In this case, I'm going to close this issue - if the default config works, it's likely a problem with your custom config rather than a bug, specifically with the open and opener rules. 

You can check https://yazi-rs.github.io/docs/configuration/yazi#open and https://yazi-rs.github.io/docs/configuration/yazi#opener for information on how to configure them correctly, or just remove them all and try adding them back one by one.

**Closed by sxyazi** 2024-10-08 03:09 UTC
Labels: bug
