### ISSUE TITLE
I cannot get the modification time of the current file from the bottom status bar

### ISSUE THREAD

**Issue by 178me** [sxyazi/yazi#1749] opened 2024-10-09 08:31 UTC
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

alacritty 0.13.2 (bb8ea18e)

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":1")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-38
    fzf              : No such file or directory (os error 2)
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/yzl178me/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

I want to have a place where I can configure the information displayed in the bottom status bar. Thank you

### Minimal reproducer

You can see it by opening yazi

### Anything else?

![image](https://github.com/user-attachments/assets/3b60db72-c9fb-429d-838c-f5fa3faf7816)

**Comment by sxyazi** [comment] 2024-10-09 08:47
Showing the filename at the bottom instead of the creation time is by design, but you can always change it yourself, there's some examples: https://yazi-rs.github.io/docs/tips

Closing as it's not even a bug

**Closed by sxyazi** 2024-10-09 08:47 UTC
Labels: bug

**Comment by 178me** [comment] 2024-10-09 08:53
Thanks, I haven’t seen `tips` before
