### ISSUE TITLE
[bug] yazi becomes very slow if tmux binds the `-n M-'['` shortcut, and the `-n M-'['` will get triggered when start yazi

### ISSUE THREAD

**Issue by guanghechen** [sxyazi/yazi#1799] opened 2024-10-17 07:40 UTC
### What system are you running Yazi on?

Windows WSL

### What terminal are you running Yazi in?

Windows Terminal Preview Version: 1.22.2702.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Homebrew 2024-09-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Homebrew 2024-09-04)

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: true

Variables
    SHELL              : Some("/home/linuxbrew/.linuxbrew/bin/fish")
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/alice/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

1. I have bound the `-n M-'['` to select the tmux previous-window
2. When I run the `yazi` in a tmux window, it will jump to other tmux window and output some mess codes, and the `yazi` will be takes a long time to enter the ui.

### Minimal reproducer

1. open windows terminal
2. run tmux (3.4)
3. run ` tmux bind -n M-'[' previous-window`
4. run `yazi`

**Comment by sxyazi** [comment] 2024-10-17 09:59
Duplicate of https://github.com/sxyazi/yazi/issues/1557 and https://github.com/sxyazi/yazi/issues/1621, please read these two issues

**Closed by sxyazi** 2024-10-17 09:59 UTC
Labels: bug

**Comment by guanghechen** [comment] 2024-10-18 10:33
Hi @sxyazi, thanks for guiding me to the discussion. I noticed that issue has been locked and I cannot  comment anymore, so just asking here. My question is that I have tried the latest window terminal preview also tested the canary version), but the issue seems still persistent, which seems not mached what the @j4james saied?

**Comment by j4james** [comment] 2024-10-19 14:27
@guanghechen My comments in #1557 were regarding the interaction between WezTerm and Windows conpty, and you're not using WezTerm. Your problem is more likely to have been caused by something in tmux (or possibly a tmux plugin) as described in https://github.com/sxyazi/yazi/issues/1621#issuecomment-2342793146.

**Comment by guanghechen** [comment] 2024-10-20 16:25
Okay, thanks for your reply. I must misunderstand your words :(.
