### ISSUE TITLE
add support display lazily loaded directory sizes like ranger

### ISSUE THREAD

**Issue by cxwx** [sxyazi/yazi#1014] opened 2024-05-08 05:41 UTC
### Please describe the problem you're trying to solve

like ranger command `vdcv` show the total size of each directory
<img width="472" alt="截屏2024-05-08 13 40 04" src="https://github.com/sxyazi/yazi/assets/6235641/ccc58697-7ce6-42cc-980a-9b1cddfd6397">

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

add a keymap like vdcv or others

**Comment by sxyazi** [comment] 2024-05-08 05:49
Duplicate of https://github.com/sxyazi/yazi/discussions/492#discussioncomment-8061404 and https://github.com/sxyazi/yazi/issues/842

**Closed by sxyazi** 2024-05-08 05:49 UTC
Labels: feature

**Comment by cxwx** [comment] 2024-05-11 06:34
already supported and lazy load ',S'
