### ISSUE TITLE
Thumbnails / previews for common file types

### ISSUE THREAD

**Issue by jreuben11** [sxyazi/yazi#1370] opened 2024-07-31 08:38 UTC
While code artifact, video file and pdf files have previews in Yazi, libreoffice and epub files do not.
In Nautilus GUI, they are viewable.

**Comment by leihaojun** [comment] 2024-07-31 09:27
unzip "test.epub" "cover.jpg" -d /tmp/yazi

It seems that this can easily extract the cover image, but I don't know how to put it in the preview

**Comment by sxyazi** [comment] 2024-07-31 15:37
Duplicate of https://github.com/sxyazi/yazi/issues/1239

**Closed by sxyazi** 2024-07-31 15:37 UTC
Labels: feature

**Comment by leihaojun** [comment] 2024-08-01 04:10
i found a plugin to preview epub 

https://github.com/kirasok/epub-preview.yazi/
