### ISSUE TITLE
Intermittent Failure in Batch File Renaming

### ISSUE THREAD

**Issue by BBOOXX** [sxyazi/yazi#833] opened 2024-03-22 07:24 UTC
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iTerm2

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.4 (e5c543c 2024-03-22)
    OS: macos-aarch64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "iTerm.app")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect: Iterm2

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /usr/share/file/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

```

</details>

### Describe the bug

Subsequent batch file renaming operations occasionally fail to change file names after the first successful attempt, with no error messages displayed.

### Expected Behavior

Perform batch renaming operations correctly

### To Reproduce

https://github.com/sxyazi/yazi/assets/7044834/8cbc7a5c-f4b3-43ad-b5ce-ed1c4ae30d35

1. Press `Ctrl+A` to select all files.
1. Press `r` for the initial batch renaming, which usually succeeds.
1. When pressing `r` again for batch renaming, file names occasionally remain unchanged without any error prompts.
1. Repeating steps 3 can reproduce the issue.

**Comment by sxyazi** [comment] 2024-03-26 03:24
Just tested with the latest main branch, and I can't reproduce it. But I reproduced it in the v0.2.4 release.

Are you sure this still exists in the latest main branch? I noticed the video you provided is from v0.2.4, not the latest main branch, so it seems to have been fixed.

**Comment by sxyazi** [comment] 2024-03-26 04:59
Closing as discussed with @BBOOXX on Yazi's Telegram group, this is a bug that has been fixed on the main branch.

**Closed by sxyazi** 2024-03-26 04:59 UTC
Labels: bug, waiting on op
