### ISSUE TITLE
Yazi as default filepicker

### ISSUE THREAD

**Issue by magdesign** [sxyazi/yazi#2079] opened 2024-12-21 23:36 UTC
### `yazi --debug` output

```Shell
no debug. feature request.
```

### Please describe the problem you're trying to solve

I'd love to use Yazi as my default, systemwide filepicker on postmarketOS/Alpine Linux with sway.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I writeup/tutorial on how to make/use Yazi as the default XDG filepicker on systems without systemd/libc.

### Additional context

So far I had no luck with editing `/usr/share/xdg-desktop-portal/sway-portals.conf`

### Checklist

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by magdesign** [comment] 2024-12-22 12:15
see:
https://github.com/sxyazi/yazi/issues/51#issuecomment-2470916427

https://github.com/sxyazi/yazi/discussions/1128#discussion-6782414

**Comment by sxyazi** [comment] 2024-12-22 12:24
Duplicate of https://github.com/sxyazi/yazi/discussions/1119

Does https://github.com/boydaihungst/xdg-desktop-portal-termfilechooser not working for you?

**Comment by magdesign** [comment] 2024-12-22 13:04
no, because `xdg-desktop-portal-termfilechooser` somehow relies on `systemd`. on alpine we have `openrc` which does not support dbus commands.

**Comment by magdesign** [comment] 2024-12-22 13:22
https://github.com/GermainZ/xdg-desktop-portal-termfilechooser/issues/19

**Comment by sxyazi** [comment] 2024-12-22 13:34
Hmm I have no idea how `xdg-desktop-portal-termfilechooser` works and am not familiar with `openrc` - I never used them myself. 

I'll tag this issue as "help wanted" to see if anyone familiar with them can offer any help.

**Comment by magdesign** [comment] 2024-12-22 22:10
got a bit further.... t
**he issue was not missing systemd, but filechooser.c had an error for not supporting arm.**

this error is fixed now and for anyone else searching to find a way to set yazi as filepicker default on postmarketos/arm, here is the writeup:

https://wiki.postmarketos.org/wiki/User:Magdesign#Filepicker

**Closed** 2024-12-23 03:19 UTC
Labels: help wanted, feature
