### ISSUE TITLE
contents of /bin are empty, but not in right-most pane or when going to /usr/bin (which /bin is symlinked to)

### ISSUE THREAD

**Issue by nalabrie** [sxyazi/yazi#1438] opened 2024-08-08 08:20 UTC
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

mintty 3.7.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (a9d2d9c 2024-08-08)
    Debug  : false
    OS     : linux-aarch64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([Sixel]))
    Emulator.detect : Unknown([Sixel])

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: true

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: tmux 3.3a

Dependencies
    file             : 5.44
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : No such file or directory (os error 2)
    fzf              : 0.38.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.12.4
    zoxide           : 0.4.3
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.6
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Environment

Running yazi nightly `a9d2d9c 2024-08-08` (or stable 0.3.0) on a Raspberry Pi 4 (Debian bookworm 12.6) with the `yazi-aarch64-unknown-linux-gnu.zip` build from the GitHub releases page.

At the moment, I am on a Windows machine using `mintty` terminal to ssh into the Pi. I can try later using ssh from another Linux machine, but I am doubtful that would make a difference. I am not able to hook the Pi directly to a monitor to test that, unfortunately.

`/bin` is a symbolic link to `/usr/bin` in this scenario. I have not found another symbolic link where this happens, only `/bin`.

### Issue

When viewing the `/` directory, the right-most pane of yazi correctly shows the contents of `/bin`. This can be seen here:
![Screenshot 1](https://github.com/user-attachments/assets/b2869363-6b80-411b-853a-7fb42e5e9777)

Then, when pressing `l`/`right arrow` to enter `/bin`, the contents are empty as shown here:
![Screenshot 2](https://github.com/user-attachments/assets/4c10ed0b-176c-4a10-b4b6-c5eb6d39798c)

When backing out of `/bin` to `/`, the right-most pane is now also empty as shown here:
![Screenshot 3](https://github.com/user-attachments/assets/1d69c05b-c3d0-4785-8357-66089a9a634a)

When going to `/usr/bin` directly, everything is shown properly, as shown below. All other symbolic links I have tested work fine with yazi, this is the one exception.
![Screenshot 4](https://github.com/user-attachments/assets/9af301b0-a034-4109-af0e-e4d581276757)

### Contents of `yazi.log`

```log
2024-08-08T08:02:01.076532Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
  at yazi-adapter/src/emulator.rs:70

2024-08-08T08:02:01.076593Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM_PROGRAM:
  at yazi-adapter/src/emulator.rs:84

2024-08-08T08:02:01.076606Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM: xterm-256color
  at yazi-adapter/src/emulator.rs:92
```

### Minimal reproducer

1. Be running Debian 12 on a Raspberry Pi 4 (aarch64)
	- Perhaps any Debian version and/or architecture would work as long as `/bin` is symbolically linked to `/usr/bin`?
2. Download and run nightly `a9d2d9c 2024-08-08` (or stable 0.3.0) yazi from GitHub releases page.
```sh
curl -#LO https://github.com/sxyazi/yazi/releases/download/nightly/yazi-aarch64-unknown-linux-gnu.zip
unzip yazi-aarch64-unknown-linux-gnu.zip
cd yazi-aarch64-unknown-linux-gnu
./yazi /
```
3. Hover over `/bin` and press `l`/`right arrow` to enter `/bin`.
4. Poof, nothing is there :(

**Comment by sxyazi** [comment] 2024-08-08 11:34
Please try https://github.com/sxyazi/yazi/pull/1439

**Comment by sxyazi** [comment] 2024-08-09 03:38
Let's go ahead and merge it first. If the issue still, please feel free to reply to this issue or create a new one.

**Comment by nalabrie** [comment] 2024-08-10 01:44
Still experiencing the same behavior in `Yazi 0.3.0 (4150f40 2024-08-10)`, but I certainly do appreciate the quick followup to this issue regardless.

**Comment by sxyazi** [comment] 2024-08-10 04:27
That's really strange. After I applied the patch, I couldn't reproduce the issue at all:

https://github.com/user-attachments/assets/2005fcaf-f601-4060-af1b-d687046e7d1f


Before applying it, I did encounter the problem where the preview wouldn't refresh and kept showing "no items" due to a loading state error. 

Could you record a video of your steps so I can catch all the details?

**Comment by nalabrie** [comment] 2024-08-10 05:05
No problem, here you go. 

https://github.com/user-attachments/assets/070d8e50-9bcd-4a8a-bd4b-888bf906d129

**Comment by nalabrie** [comment] 2024-08-10 05:43
I just tried the stable 0.3.0 and that same nightly build on my Fedora system (x86_64) and **neither** have that issue. It is only on the Raspberry Pi. Very strange.

Another note: in the video I posted, there is a flicker when pressing `right arrow` on `/bin`. That seems to be a glitch with the terminal I am using on Windows to ssh into the Pi. When I ssh from the Fedora system, there is no flicker. Just wanted to clarify because the flicker makes it look like it loaded correctly briefly and then went away, when that isn't the case.

Here is a similar video from Fedora connecting to the Pi via ssh

https://github.com/user-attachments/assets/20163c90-b3d4-4551-a188-f190ecbf373c

**Comment by nalabrie** [comment] 2024-08-10 18:19
When I reboot the Pi, the contents of `/bin` show up correctly! However, the first entry in `/bin` looks like this: 
![image](https://github.com/user-attachments/assets/21ef8e5c-4147-4845-97d5-a4f51688a421)
When entering that `X11 -> .` directory and then backing out back to `/`, the same issue occurs again when entering `/bin`, even when relaunching yazi. I hope that helps, this is a very weird behaving bug.

**Comment by sxyazi** [comment] 2024-08-26 23:44
Unfortunately, I still can't reproduce it.

I'll keep this issue open for a while to see if anyone else encounters a similar problem and can help with debugging it at the code level.

**Comment by sxyazi** [comment] 2024-10-06 05:06
This issue has been open for 2 months, no other users have reported encountering it, I can't reproduce it either, so I'm going to close it since it's not doable for me and no one can help :(

My best guess is that this is related to your environment, or it's already been fixed in recent versions.

**Closed by sxyazi** 2024-10-06 05:06 UTC
Labels: bug, help wanted, cant reproduce
