### ISSUE TITLE
custom keymap [input] 'escape' does not exit insert mode from input field.

### ISSUE THREAD

**Issue by virtual-voyager** [sxyazi/yazi#1890] opened 2024-11-07 11:38 UTC
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty v0.37.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (6001f3c 2024-11-07)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":1")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("4520b30d498daca8079365bdb909a8dea38e8d55_1730977527_1743488499")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.41.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    fdfind           : No such file or directory (os error 2)
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Describe the bug

I wanted to map the "ü" key to mirror the behaviour of \<ESC\> and would have expected it to exit insert mode in input fields, but only \<ESC\> works to exit insert mode.

### Minimal reproducer

- Map a key to [input] 'escape'
- open a input field in yazi (e.g. by pressing "a")
- press the mapped key
- the pressed key is passed to the input field and does not escape insert mode

### Anything else?

I mapped the "ü" key in my `keymap.toml` like this:

```
[[manager.prepend_keymap]]
on   = "ü"
run  = 'escape'
desc = "Exit visual mode, clear selected, or cancel search"

[[tasks.prepend_keymap]]
on   = "ü"
run  = 'close'
desc = "Close task manager"

[[select.prepend_keymap]]
on   = "ü"
run  = 'close'
desc = "Cancel selection"

[[input.prepend_keymap]]
on   = "ü"
run  = 'escape'
desc = "Go back the normal mode, or cancel input"

[[confirm.prepend_keymap]]
on   = "ü"
run  = 'close'
desc = "Cancel the confirm"

[[help.prepend_keymap]]
on   = "ü"
run  = 'escape'
desc = "Clear the filter, or hide the help"
```

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment] 2024-11-07 12:20
How can I test it? I mean, how do I type "ü"? Is it a character I can type on my standard English layout keyboard?

**Comment by sxyazi** [comment] 2024-11-07 12:47
> type "ü" just like any normal character

If I understand correctly, it works like any other key in the letter area of the keyboard right? 

If it's the case, i.e. a printable character, not a combo like Ctrl/Shift/Alt or a special function key like `Esc` or `F1`-`F19`, then that's by design — the printable characters in the `[input]` are only meant to be used in insert mode, while only non-printable characters work in normal mode.

At the same time, I can't reproduce this issue with other components. For example, I mapped `t` to the `[manager]`, but when I enter visual mode (`V`) and press `t`, it just exits visual mode:

```
[[manager.prepend_keymap]]
on  = "t"
run = "escape"
```

**Comment by sxyazi** [comment] 2024-11-07 13:36
This design simplifies implementation because if printable characters were allowed to bind normal mode commands in insert mode, and multiple keystrokes were specified (like binding "jj" to escape):

```toml
[[input.prepend_keymap]]
on  = [ "j", "j" ]
run = "escape"
```

then after pressing the first "j", the state would have to be set as "pending", waiting to see the next action of the user before determining the behavior. This would require introducing some kind of timeout mechanism and state machine, which is a complex and track design

Considering that Yazi's input component is a simplified version of Vim, fully replicating Vim's behavior isn't the goal here, I'm going to close this issue as not planned

**Closed by sxyazi** 2024-11-07 13:36 UTC
Labels: invalid
