### ISSUE TITLE
SSH Link

### ISSUE THREAD

**Issue by wyne** [sxyazi/yazi#1417] opened 2024-08-06 02:24 UTC
### `yazi --debug` output

<details>

N/A

</details>

### Please describe the problem you're trying to solve

Midnight Commander is the only terminal file manager I've found that can easily connect to another host over ssh and transfer files. This is very helpful for selecting a few config files, seeing local and remote directories side by side, and copying them over.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

I'd like to be able to connect to a remote SSH host via FISH (FIle transfer over SHell filsystem"

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment] 2024-08-06 02:30
Duplicate of https://github.com/sxyazi/yazi/issues/611, it's already on the roadmap

**Closed by sxyazi** 2024-08-06 02:30 UTC
Labels: feature
