### ISSUE TITLE
The 'input' escape does not work as expected

### ISSUE THREAD

**Issue by Thanajor** [sxyazi/yazi#1507] opened 2024-08-17 16:57 UTC
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot v.1.18.1

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (Nixpkgs 2024-08-01)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/run/current-system/sw/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : 24.07
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/thanajor/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Hi, I hope you are having a nice day.

I wrote this issue why: In the Yazi documentacion.

The declare `escape` in the [input](https://yazi-rs.github.io/docs/configuration/keymap#input.escape) section, is described as:  Go back the normal mode, or cancel input.

This functionality works correctly with keybindings such as `Ctrl D`, is able to return to normal mode and escape, but with keybinds as `jk`does not go back  the normal mode only works for cancel input.

I recognize that in very few cases are you going to want a keybind like this. But it should be stated somewhere that this shortcut will not work.

[fixthis.webm](https://github.com/user-attachments/assets/880fd5f3-f0a6-4751-a5bf-0722b5f90555)

### Minimal reproducer

Wrote this config in your keymap.toml

```keymap.toml
[[input.prepend_keymap]] 
desc = "Escape with jk"
on = ["j", "k"]
run = ["escape"]
```

**Comment by sxyazi** [comment] 2024-08-18 09:51
This is by design. Yazi's input component is a simplified version of the Vi editor. In insert mode, `j` and `k` are treated as regular characters, so they can't be bound to commands simultaneously. This is because doing so would require introducing timers and delays, which is a hacky approach that was deliberately avoided during design. 

If you really need `j k` to exit insert mode, it should be possible to achieve this through the plugin system in the future. The plugin system already provides the `ya.input` API, which means it can access user input in real-time. To make this work, it would just need the ability to modify user input — when a user types `j k` in insert mode, it would delete those characters and return to normal mode. I believe this will become possible as the plugin system evolves.

Closing as it's the expected behavior not a bug

**Closed by sxyazi** 2024-08-18 09:51 UTC
Labels: bug
